### ISSUE TITLE
PR is not appoved if there is no new issue on a code but there are some issues in overview comment

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#102]
See also https://github.com/AmadeusITGroup/sonar-stash/issues/25

**Comment by kingoleg** [comment]
At 1.2 version

**Comment by t-8ch** [comment]
So there is no comment but the issue is listed in the overview?
Can you run the scanner with debugging enabled and paste the output to a Gist?
(Make sure to remove passwords, especially in `Authorization` HTTP Headers)
Best you use a test instance with dummy passwords.

**Comment by kingoleg** [comment]
Sorry, cannot repeat it on the master

**Comment by kingoleg** [comment]
Master's behavior is very strange. No one repo it does not find new issues, adds summary comment about it and approves a PR. On other repo it breaks in the middle:

build	20-Mar-2017 21:13:29	[INFO] ANALYSIS SUCCESSFUL
build	20-Mar-2017 21:13:29	[INFO] Executing post-job org.sonar.plugins.stash.StashIssueReportingPostJob
build	20-Mar-2017 21:13:30	[INFO] SonarQube issues reported to Stash by user "sonarqube" have been reset
build	20-Mar-2017 21:13:30	[INFO] New SonarQube issues have been reported to Stash.
build	20-Mar-2017 21:13:30	[INFO] SonarQube analysis overview has been reported to Stash.
build	20-Mar-2017 21:13:30	[ERROR] Unable to reset pull-request approval
build	20-Mar-2017 21:13:30	org.sonar.plugins.stash.exceptions.StashClientException: Unable to change status of pull-request mexos #963. Received 404: com.atlassian.bitbucket.project.NoSuchProjectException: Project PullRequestRef{project=MEXOS, repository=mexos, pullRequestId=963} does not exist.
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.client.StashClient.validateResponse(StashClient.java:298) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.client.StashClient.performRequest(StashClient.java:288) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.client.StashClient.delete(StashClient.java:263) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.client.StashClient.resetPullRequestApproval(StashClient.java:221) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.StashRequestFacade.resetPullRequestApproval(StashRequestFacade.java:96) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.StashIssueReportingPostJob.postInfoAndPRsActions(StashIssueReportingPostJob.java:166) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.StashIssueReportingPostJob.updateStashWithSonarInfo(StashIssueReportingPostJob.java:115) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:55) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:55) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:87) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.6.jar:na]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch2921838168315020655.jar:na]
build	20-Mar-2017 21:13:30		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-api-2.8.jar:na]
build	20-Mar-2017 21:13:30		at com.sun.proxy.$Proxy23.execute(Unknown Source) [na:na]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonar-scanner-api-2.8.jar:na]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-api-2.8.jar:na]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.maven.bootstrap.ScannerBootstrapper.execute(ScannerBootstrapper.java:78) [sonar-maven-plugin-3.2.jar:na]
build	20-Mar-2017 21:13:30		at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:122) [sonar-maven-plugin-3.2.jar:na]
build	20-Mar-2017 21:13:30		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106) [maven-core-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863) [maven-embedder-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288) [maven-embedder-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at org.apache.maven.cli.MavenCli.main(MavenCli.java:199) [maven-embedder-3.3.9.jar:3.3.9]
build	20-Mar-2017 21:13:30		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
build	20-Mar-2017 21:13:30		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
build	20-Mar-2017 21:13:30		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
build	20-Mar-2017 21:13:30		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
build	20-Mar-2017 21:13:30		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
build	20-Mar-2017 21:13:30

**Comment by t-8ch** [comment]
I propose we declare this as fixed then.

**Comment by t-8ch** [comment]
Sorry, your last comment loaded after I posted this...

**Comment by t-8ch** [comment]
`com.atlassian.bitbucket.project.NoSuchProjectException: Project PullRequestRef{project=MEXOS, repository=mexos, pullRequestId=963} does not exist.`

Could you verify that the project PR actually exist?

**Comment by kingoleg** [comment]
Exists. I will continue to investigate the issue

**Comment by kingoleg** [comment]
Ok. This is the situation now.

sonar-stash found new issues, added per line comments per issue, added summary comment then:

build	21-Mar-2017 11:23:13	[INFO] ANALYSIS SUCCESSFUL
build	21-Mar-2017 11:23:13	[INFO] Executing post-job org.sonar.plugins.stash.StashIssueReportingPostJob
build	21-Mar-2017 11:23:13	[INFO] SonarQube issues reported to Stash by user "sonarqube" have been reset
build	21-Mar-2017 11:23:14	[INFO] New SonarQube issues have been reported to Stash.
build	21-Mar-2017 11:23:14	[INFO] Code coverage report has been reported to Stash.
build	21-Mar-2017 11:23:14	[INFO] SonarQube analysis overview has been reported to Stash.
build	21-Mar-2017 11:23:14	[ERROR] Unable to reset pull-request approval
build	21-Mar-2017 11:23:14	org.sonar.plugins.stash.exceptions.StashClientException: Unable to change status of pull-request Test #25. Received 404: com.atlassian.bitbucket.project.NoSuchProjectException: Project PullRequestRef{project=Test, repository=Test, pullRequestId=25} does not exist.
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.client.StashClient.validateResponse(StashClient.java:298) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.client.StashClient.performRequest(StashClient.java:288) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.client.StashClient.delete(StashClient.java:263) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.client.StashClient.resetPullRequestApproval(StashClient.java:221) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.StashRequestFacade.resetPullRequestApproval(StashRequestFacade.java:96) ~[sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.StashIssueReportingPostJob.postInfoAndPRsActions(StashIssueReportingPostJob.java:166) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.StashIssueReportingPostJob.updateStashWithSonarInfo(StashIssueReportingPostJob.java:115) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:55) [sonar-stash-plugin-1.3.0-SNAPSHOT.jar:na]
build	21-Mar-2017 11:23:14		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:65) [sonar-scanner-engine-shaded-5.6.6.jar:na]
....

**Comment by kingoleg** [comment]
Hm. It looks like it cannot remove its approval...

I created an other PR without new sonar issues. And sonar-stash successfully approval the new PR

**Comment by t-8ch** [comment]
`com.atlassian.bitbucket.project.NoSuchProjectException: Project PullRequestRef{project=Test, repository=Test, pullRequestId=25} does not exist.`
Is this the correct pullrequest?

**Comment by t-8ch** [comment]
I am asking because the error message is created by bitbucket itself. So if we ask for the right pull request and it is not found this indicates an issue with bitbucket.

**Comment by kingoleg** [comment]
It can be that you call bitbucket with different API? And in one case it is case sensitive, for example.

The real project is "TEST" and real repository name is "Test" and real slug name is "test".

It's very strange that is can add some comments to this PR but cannot unapprove it

**Comment by t-8ch** [comment]
We are using only one set of APIs.
Did you configure the plugin with the correct names?

**Comment by kingoleg** [comment]
Sure, If I see a new comments in PR, how it can be incorrect set up?

**Comment by t-8ch** [comment]
As you said yourself, some APIs may be case sensitive and some not.
So maybe the configuration has a different casing and works for some api calls.

**Comment by kingoleg** [comment]
Check StashClient lines 217 & 222:

```
  public void approvePullRequest(PullRequestRef pr) throws StashClientException {
    String request = MessageFormat.format(API_ONE_PR_APPROVAL, baseUrl, pr.project(), pr.repository(), pr.pullRequestId());
    post(request, null, MessageFormat.format(PULL_REQUEST_APPROVAL_POST_ERROR_MESSAGE, pr.repository(), pr.pullRequestId()));
  }
  
  public void resetPullRequestApproval(PullRequestRef pr) throws StashClientException {
    String request = MessageFormat.format(API_ONE_PR_APPROVAL, baseUrl, pr);
    delete(request, HttpURLConnection.HTTP_OK, MessageFormat.format(PULL_REQUEST_APPROVAL_POST_ERROR_MESSAGE, pr.repository(), pr.pullRequestId()));
  }
```

In resetPullRequestApproval you replace not all parameters, and replace {1} with pr.toString() instead of pr.project()

Please, avoid to use MessageFormat.format and integer binding, and use unit tests :)

PR with fix in a way

**Comment by kingoleg** [comment]
Fixed in https://github.com/AmadeusITGroup/sonar-stash/pull/105

**Comment by t-8ch** [comment]
Thanks!
This should probably changed to use a URI template library
