### ISSUE TITLE
Does this work with sonar-scanner too?

### ISSUE THREAD

**Issue by tknerr** [AmadeusITGroup/sonar-stash#104]
I was wondering whether this plugin needs to be installed on the sonarqube server, or whether it would also work locally with `sonar-scanner` in preview mode (where quality profiles are fetched from the server, but no analysis results are uploaded)

As you are using `sonar-runner -Dsonar.analysis.mode=preview ...` on the server, I was wondering if you couldn't use `sonar-scanner -Dsonar.analysis.mode=preview ...` on a CI build node too.

Can you?

**Comment by t-8ch** [comment]
SonarQube plugins are always installed on the server.
The scanner engine (sonar-scanner, mvn sonar:sonar, etc...) will download all plugins from the server at runtime.
This means it does not matter where you execute the scanner (on the server, on the CI nodes), as long as the scanner can connect to the server all plugins are executed.

**Comment by t-8ch** [comment]
The mode does also not matter. (It does not work with SonarQube 5.1.0, but that was bug)

**Comment by tknerr** [comment]
@t-8ch thanks for the explanation!

As for the communication path, does `sonar-scanner` talk directly to the bitbucket REST API, or does the communication go via the sonarqube server?

**Comment by t-8ch** [comment]
The communication is direct.

**Comment by tknerr** [comment]
@t-8ch thanks!
