### ISSUE TITLE
Check negative evolution until we reach minimum ratio only

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#110]
The plugin should respect common-java:InsufficientBranchCoverage, common-java:InsufficientLineCoverage setup, minimumBranchCoverageRatio and/or minimumLineCoverageRatio respectively. If the file coverage degrades but still is more then the minimum ratio, PR should be approved. It should not be a fight for the last coverage ratio.

https://github.com/AmadeusITGroup/sonar-stash/issues/58

**Comment by t-8ch** [comment]
Moved to AmadeusITGroup/sonar-coverage-evolution#2
