### ISSUE TITLE
Support for multi-level maven project where parent lives on the same level directory as child modules

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#111]
Currently the plugin does not work with next project structure:

/parent/pom.xml
/module1/pom.xml
/module2/pom.xml

$ mvn sonar:sonar ... -fparent/pom.xml

**Comment by t-8ch** [comment]
Hm, can you try to specify the base dir explicitly?
The basedir should be provided by the runner.
I am still figuring out how the plugin should handle this

**Comment by kingoleg** [comment]
sonar maven plugin set this base dir automatically.

What the value you what to use? `/parent/../` (`/`)? The directory, where `$ mvn` run?

**Comment by t-8ch** [comment]
The root of your git directory.

**Comment by kingoleg** [comment]
It looks like it works.

**Comment by t-8ch** [comment]
Ok, honestly I think this is the real solution instead of adding more configuration to this plugin.
What is your opinion?

Of course this should be documented prominently.

**Comment by kingoleg** [comment]
Let me run several tests. I will let you know.

May be I have to use the same property on regular sonar run too.

**Comment by kingoleg** [comment]
Yep, it found all issues as new for now:)

**Comment by t-8ch** [comment]
Ok, so lets close this and document it.

**Comment by kingoleg** [comment]
I'm still in the middle. Full sonar scan takes time for my project

**Comment by t-8ch** [comment]
Does it trigger a full scan when passing the basedir explicitly?

**Comment by kingoleg** [comment]
How I can understand this?

**Comment by t-8ch** [comment]
Ah, sorry. I misunderstood your comment.
I understood "I'm still in the middle" as "I am not sure about this assessment".

**Comment by kingoleg** [comment]
Ok, Setting project base dir breaks maven sonar integration.

Without it, each module calculates base dir individually. Based on module directory.

With hardcoded base dir, this calculation doesn't work.

It causes a break of all relatively to module folder calculation maven/sonar functionality. For example, exclusions/inclusions.

For my opinion - we should not set up project base dir for maven project.

**Comment by kingoleg** [comment]
Just got a `java.lang.OutOfMemoryError: Java heap space` on server because of it

**Comment by kingoleg** [comment]
I propose to use working directory instead of project base dir in getIssuePath pathResolver

**Comment by kingoleg** [comment]
Do you what PR to master or to split branch?

**Comment by t-8ch** [comment]
To master please.
I will also try to reproduce this on monday.

**Comment by kingoleg** [comment]
https://github.com/AmadeusITGroup/sonar-stash/pull/115
