### ISSUE TITLE
Travis CI build failures timeout

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#117]
Sometimes travis build failures because of timeouts

See https://github.com/AmadeusITGroup/sonar-stash/pull/115 for example:

```
Tests in error: 

  StashClientTest.testDeleteTaskOnComment:333 » StashClient java.util.concurrent...
```

**Comment by re-schneider** [comment]
This issue has been raised internally and @t-8ch updated the tests to be more stable in travis (for example in commit 78b1a1a441a28464c6d7807fb7fe8bd79c6d92ac).
