### ISSUE TITLE
Merge with SonarCommunity/sonar-github

### ISSUE THREAD

**Issue by juherr** [AmadeusITGroup/sonar-stash#12]
My naive point of view see sonar-stash and SonarCommunity/sonar-github equivalent, where the only difference is the backend api.
A pull-request facade api is maybe enough with github/stash implementations.

Why not merging the 2 plugins and share the effort on feature?

**Comment by almorelle** [comment]
:+1:

**Comment by juherr** [comment]
In fact, I've just discovered a Bitbucket Cloud plugin already exists too: https://github.com/mibexsoftware/sonar-bitbucket-plugin

**Comment by ray-schneider** [comment]
Hi,

thanks for the interest in this plugin. I had exactly the same reaction when I joined the team.

However, back when the need was identified, SonarSource was developing the sonar-github plugin and was not planning any extension nor opening the ongoing plugin to external contribution. Hence the start of this plugin.

The same way, I guess that the guys at Mibex Software faced a need that was not addressed and started their plugin (I am not aware of any attempt to extend this plugin but you should ask them).

In a perfect world, I agree that it would be great to have all three connectivity within the same plugin (and the SonarSource sonar-github would be a good candidate as it is the product dev). But it will require some migration effort on behalf of all the dev teams to get there.

I will say that it is a long-term goal for this plugin...
