### ISSUE TITLE
No issues found in SonarQube 6.3

### ISSUE THREAD

**Issue by pedromauriciocosta** [AmadeusITGroup/sonar-stash#121]
I had the plugin working fine with SonarQube 6.2. But once I updated to 6.3 it stopped posting any issues.
Has anyone encountered this problem?

**Comment by t-8ch** [comment]
I am not aware of any reports.

**Comment by t-8ch** [comment]
Can you provide debug logs? (Please remove http credentials)

**Comment by marcjay** [comment]
I'm seeing this as well, it's because api/resources has been removed in 6.3: https://sonarqube.com/web_api/api/resources

Excerpt from log:
`GET /sonar/api/resources?resource=XXXXX&metrics=line_coverage&format=json HTTP/1.1`
...
`Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404
`

**Comment by t-8ch** [comment]
So without the coverage feature everything works?
This is unfortunate... The other API has only been introduced in 5.4, so it is not available in 5.2 LTS.

**Comment by kingoleg** [comment]
sonar-stash can support both API, why not?

**Comment by t-8ch** [comment]
I was mistaken. 5.6 is the LTS. As the plugin will only support 5.6 anyways this will be migrated to the new API.

**Comment by t-8ch** [comment]
This will also have to wait until the coverage part is split into its own plugin.
Currently the sonar ws client needs same maven trickery to work and I'd like to keep this complexity out of the sonar-stash plugin.

**Comment by pedromauriciocosta** [comment]
Thanks for that. Any idea when could we have a working version?

**Comment by olafgeibig** [comment]
I just want to install the plugin... So now I'm confused what is working and what is broken. The original post says that issues are not posted, but later on you say that coverage is the problem. Currently I'm not so much interested in the coverage feature as this is already solved for me in our Jenkins pipeline. I rather want that issues are commented on the PR.

**Comment by t-8ch** [comment]
@olafgeibig Currently the coverage feature are broken on SonarQube 6.3. The rest should work.

**Comment by michalmikee** [comment]
Maybe this is the same problem: https://github.com/AmadeusITGroup/sonar-stash/issues/120

**Comment by marcjay** [comment]
@michalmikee I think you're right - the line_coverage issue I was also seeing in the logs might have been a red-herring

**Comment by marcjay** [comment]
I just tested PR #127 and this also solved the issue for me - I'm now seeing issues showing up in PRs 😄

**Comment by jannylund** [comment]
Any ETA on releasing 1.3.0? I built with PR #127 as well and finally things work properly.

**Comment by t-8ch** [comment]
#127 Is now in 1.3.0-rc1, please test.

**Comment by jannylund** [comment]
I can confirm this works properly in 6.3!
