### ISSUE TITLE
Additional Cipher Suites

### ISSUE THREAD

**Issue by crgardner** [AmadeusITGroup/sonar-stash#122]
My bitbucket server uses TLS.  When attempting to get the sonar user from bitbucket, my sonar-runner encountered a handshake_failure.  I did a bit of research and determined that netty, used by StashClient via the AsyncHttpClient, did not include whatever cipher suite my bitbucket server wants to use.

I was able to overcome the problem by changing StashClient.createHttpClient() to pass all the cipher suites supported by the JVM to the DefaultAsyncHttpClientConfig.Builder. 

`  AsyncHttpClient createHttpClient(String sonarQubeVersion){
      
    try {
        SSLContext context = SSLContext.getDefault();
        SSLSocketFactory sf = context.getSocketFactory();
        String[] cipherSuites = sf.getSupportedCipherSuites();
        return new DefaultAsyncHttpClient(
                new DefaultAsyncHttpClientConfig.Builder().setEnabledCipherSuites(cipherSuites).setUserAgent(getUserAgent(sonarQubeVersion)).setHandshakeTimeout(30000).build()
                );
    } catch (NoSuchAlgorithmException e) {
        throw new IllegalStateException(e);
    }
  }`

Please provide an option to supply additional cipher suites.

**Comment by t-8ch** [comment]
Can you try whether the default `HTTPUrlConnection` can connect to the bitbucket server?

**Comment by t-8ch** [comment]
Can you also try to set the standard `https.cipherSuites` system property.

**Comment by crgardner** [comment]
I didn't try HTTPUrlConnection, but I did set the https.cipherSuites property.  That didn't help, at least in my environment.

**Comment by t-8ch** [comment]
Can you try: `org.asynchttpclient.enabledCipherSuites`?

**Comment by crgardner** [comment]
Setting org.asynchttpclient.enabledCipherSuites to the netty-excluded cipher suite (TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA) works, at least in StashClientTest.testGetUser().

Is there any chance something could be done in the plugin so that users don't need to worry about setting the command line argument?

**Comment by t-8ch** [comment]
This cipher was probably disabled for a reason.
This seems to be a platform (configuration) and not a plugin issue.
