### ISSUE TITLE
Do we need to run this on every single PR?

### ISSUE THREAD

**Issue by esyd1pi0** [AmadeusITGroup/sonar-stash#124]
Question:
After installing the plugin on the sonarqube server, do developers need to invoke sonar-runner on every single PR they open? Under the "How to run the plugin" section in the read me it says:
_sonar-runner -Dsonar.analysis.mode=incremental -Dsonar.stash.notification -Dsonar.stash.project=<PROJECT> -Dsonar.stash.repository=<REPO> -Dsonar.stash.pullrequest.id=<PR_ID> -Dsonar.stash.password=<STASH_PASSWORD>..._. There is  PR ID parameter that we need to pass, hence the question.
But also reading the "How to activate the coverage inside the pull-request" section it looks like this plugin will run automatically on every PR once it is installed on the sonarqube server.
Confused.

**Comment by t-8ch** [comment]
Yes, this needs to run on every single PR. Commonly this is done by a continuous integration system that builds every PR anyways.
This can not be triggered by the SonarQube server.

**Comment by esyd1pi0** [comment]
Thanks.
