### ISSUE TITLE
Could not parse JSON response: The unexpected token END()

### ISSUE THREAD

**Issue by mdanielak** [AmadeusITGroup/sonar-stash#126]
Hello,
I'm using Sonarqube 5.6.3, everything works fine when I'm analysing let's call it "small-medium" pull-requests. When I try to analyse bigger pull-request (~250 issues and a lot of new files), after the analysis is finished plugin throws exception:
`Unable to get Stash differential report from Stash
org.sonar.plugins.stash.exceptions.StashClientException: Could not parse JSON response org.json.simple.DeserializationException: The unexpected token END() was found at position 1261962. Fix the parsable string and try again.`
Below exception there is a huge json.
I guess the problem is in the size of comments to be added to bitbucket. Is there anything I can do?

Thank you,
Maciek

**Comment by t-8ch** [comment]
Hi @mdanielak which version of bitbucket / sonar-stash are you using?
We were seeing something similar internally.
Enabling compression in the http client was enough to work around the issue.
Could you try a build with 315369c160669f19d33476b5fc5e1376c4eef48f applied?

**Comment by mdanielak** [comment]
Sorry for the late reply.
I'm using Atlassian Stash v3.5.1. I have tried with 315369c and got the same output.
`org.sonar.plugins.stash.exceptions.StashClientException: Could not parse JSON response Unexpected token END OF FILE at position 1249312.`

**Comment by t-8ch** [comment]
When the data returned from stash is broken there is not much the plugin can do.
It is also not an issue with the plugin, so I will close this.
The best shot in debugging would be to check the URL that is used by the plugin and try to access it via curl and validate that the JSON is broken there too. (Use `curl ... | python -m json.tool`)
If you can reproduce it using curl you can probably raise a ticket with your internal stash team or to atlassian directly.

**Comment by mdanielak** [comment]
I checked as you said, with `curl pathToPull-RequestDiff | python -m json.tool` and the response I got from bitbutcket is huge but fine. It has 93512 lines and 4.4MB. 
I have the invalid json which is printed after the stash.StashIssueReportingPostJob makes an exception and ends unexpectedly prematurely. I compared those two jsons, mapped the incorrect on the correct one and it looks like incorrect one ends at line 90319. 
My question is - do you have some buffer length for storing the json? I still think that this is the problem with the plugin.

**Comment by t-8ch** [comment]
I don't think the size should be a problem. I just tested it with a 11MB json and it worked fine.

**Comment by t-8ch** [comment]
There is now also #128 that uses a streaming json parser although I highly doubt that this is the issue.

**Comment by mdanielak** [comment]
It looks like the problem exists only on Atlassian Stash v3.5.1. After upgrading to Atlassian Bitbucket v4.13.0 it is gone. Thank you for all your help, I'm closing the issue now.
