### ISSUE TITLE
Report issue when total code coverage is reduced

### ISSUE THREAD

**Issue by nikhiljain2910** [AmadeusITGroup/sonar-stash#131]
For now , the plugin reports issues when the line coverage is reduced on the file .

However , if issues are reported on decrease of total code coverage , it will cover more scenarios like : 
* A new source file is added with no tests .
* An existing source file that has 0% coverage is modified and no tests are created to cover the file. 

Please provide your feedback. Thanks

**Comment by gafl** [comment]
Hello, I am willing to create a pull request for this addition, but would like a little feedback on design options before proceeding.

Firstly, I noticed that the request as transcribed here may not be clear for all. In the two cases described above the coverage figure does not actually decrease, but 0% coverage on a new or modified file is not good, and we'd like an issue to be reported, i.e. when the return value of `CoverageUtils.calculateCoverage()` == 0%.

Regarding design, a new rule could be defined by the existing `CoverageRule` class, or a new `ZeroCoverageRule` could be created to define it (in the latter case, maybe `CoverageRule` should be renamed `DecreasingCoverageRule`?).

I think that in both cases the rule check and issue creation could be done in the `CoverageSensor`, it already calculates the relevant coverage value.

Do you have any opinions on this?

Gary

**Comment by t-8ch** [comment]
@nikhiljain2910 
This sounds reasonable.
However the plugin API does not allow us to distinguish between those two cases.
So I would go with what @gafl explains:
If the coverage is 0, create an issue.

This should be a different rule than the existing one. However I would keep the definition of this rule in the CoverageRule file.

**Comment by nikhiljain2910** [comment]
@t-8ch 
Thanks for your reply.

**Comment by gafl** [comment]
@nikhiljain2910 
I'm a bit lost, @t-8ch seems to agree with the feature proposal and solution outline, why did you close the ticket?

**Comment by nikhiljain2910** [comment]
@gafl Yes, you are correct . The issue should not be closed . It was closed by mistake . I will reopen it . Thanks

**Comment by t-8ch** [comment]
Moved to AmadeusITGroup/sonar-coverage-evolution#1
