### ISSUE TITLE
all new issues are not reported due to "Issue XXXX is not linked to a file"

### ISSUE THREAD

**Issue by Ferguzz** [AmadeusITGroup/sonar-stash#134]
sonarqube 6.3.1.21392, SonarQube Scanner 3.0.3.778

i see this for every new issue.

i notice that when i run with `sonar.issuesReport.html.enable`, a similar process of parsing new issues and writing some output is occurring.  this works correctly.  any ideas what is going on?

**Comment by t-8ch** [comment]
Hi @Ferguzz ,

what version of the plugin are you using?
Can you explain the layout of your repository? (modules, etc)
Did you set `sonar.stash.repository.root`?

**Comment by Ferguzz** [comment]
plugin version 1.2.0.  i've tried several simple repository layouts to get this working and get the same issue with all of them.  i have tried setting sonar.stash.repository.root to a few different paths for each configuration with no luck.

**Comment by t-8ch** [comment]
The repository root setting only works in 1.3.0. Can you try it with the new version?

Did you try a simple layout with one module, where the pom.xml is in the top-level directory (assuming a maven project, and using mvn `sonar:sonar`)

**Comment by Ferguzz** [comment]
thank you.  upgrading to 1.3.0-rc1 fixed the issue.
