### ISSUE TITLE
Release date version 1.3.0

### ISSUE THREAD

**Issue by rodikal** [AmadeusITGroup/sonar-stash#136]
Hi,

When will version 1.3.0 be released? The changelog for 1.3.0-rc1 states:
> The scheduled release date for 1.3.0 is 2017-06-19.

I'm asking this because we're waiting for #46 and we're not allowed to install release candidates on our production sonarqube. 1.3.0-rc1 is working in our test sonarqube.

**Comment by t-8ch** [comment]
@rodikal 
My mistake, I thought it was supposed to be released this week (and had technical difficulties yesterday)
The release will be in a few minutes.

**Comment by re-schneider** [comment]
https://github.com/AmadeusITGroup/sonar-stash/releases/tag/1.3.0
