### ISSUE TITLE
sonar bitbucket server plugin-unable to fetch data from sonar qube server

### ISSUE THREAD

**Issue by srinivas012345** [AmadeusITGroup/sonar-stash#138]
Hi,
 
We are using sonar bitbucket server plugin to analyse the pull request.
we have configured all the required settings.We ran the build using gradle build script. Below the sonarqube properties
```gradle
sonarqube {
  properties {
    property "sonar.host.url", "http://srmsbox01:8180"
    property "sonar.sources", "${projectDir}/src,${projectDir}/WebContent/js/application,${projectDir}/WebContent/cuwi-ng"
    property "sonar.projectKey", "com.siriusxm.de:sirius_uwi_cuwi:project-OAC_EBILL"
    property 'sonar.branch', "feature/DE-810-gradle-task-to-retrieve-sms-version-new"
  }
}
```
The build was success and it created the analysis in the sonar qube server. how ever when we create and access pull request. we are getting below message
"Was not able to fetch data for Sonar project `com.siriusxm.de:sirius_uwi_cuwi:project_OAC_EBILL:project_OAC_EBILL`. Either the build is not finished yet, your pull request has not been analyzed or a non-existing Sonar project is referenced. You can configure the referenced Sonar project in the repository settings."

Why its appending project key twice instead of branch name `com.siriusxm.de:sirius_uwi_cuwi:project_OAC_EBILL:project_OAC_EBILL` and trying to pull the details from sonar server

Ideally the sonar bit bucket server plugin should pull the analysis details with following key 
`com.siriusxm.de:sirius_uwi_cuwi:project_OAC_EBILL:feature/DE-810-gradle-task-to-retrieve-sms-version-new`.
 
The project key created in sonar qube server is:
`com.siriusxm.de:sirius_uwi_cuwi:project_OAC_EBILL:feature/DE-810-gradle-task-to-retrieve-sms-version-new`
 
If we change the project key and run the build again, the new analysis is created with new project key in sonarqube server. but when we access pull request, its giving different message(the error message is getting switched).
 
We tried all the options but did not success.
 
please help.

**Comment by t-8ch** [comment]
Hello @srinivas012345 ,

Please provide the following information:
* version of sonarqube
* version of sonar-stash
* Layout of your source code (single/multimodule, any special settings)
* Command you use the execute the steps you are mentioning.

**Comment by t-8ch** [comment]
Where does the string "Was not able to fetch data for Sonar project" appear?
In the log of the sonar scanner or the message on the pullrequest?

**Comment by srinivas012345** [comment]
Hi,
Thanks for the reply.Here is the info

version of sonarqube   
	- Version 6.3 (build 19869)
version of sonar-bitbucket 
	- Atlassian Bitbucket v4.8.5
Layout of your source code (single/multimodule, any special settings) 
	- Its a multi module project(project1 is the main project, having dependencies on proj2, proj2, proj3,proj4). no special settings.

Command you use the execute the steps you are mentioning  
    -clean sonarqube

Where does the string "Was not able to fetch data for Sonar project" appear?
In the log of the sonar scanner or the message on the pullrequest?

 - The message is displayed when we access the pull request in bitbucket server.

**Comment by srinivas012345** [comment]
![sonarbitbucketserver_pull request_error](https://user-images.githubusercontent.com/30087546/28137407-2c869614-671b-11e7-88e0-c39d177c7fe6.JPG)

**Comment by srinivas012345** [comment]
![image](https://user-images.githubusercontent.com/30087546/28137467-655fb20e-671b-11e7-8c6f-26b4ad59762c.png)

**Comment by t-8ch** [comment]
@srinivas012345 The plugin you are using is not the one from this repository.
I can't really help you and will close this issue.
