### ISSUE TITLE
The plugin should be able remove its comments

### ISSUE THREAD

**Issue by juherr** [AmadeusITGroup/sonar-stash#14]
I removed some rules on sonar but the associated plugin comments are still there after another analyse.
I suppose the plugin only add/update comments but don't remove them.

**Comment by acopet** [comment]
To optimize the request number to Stash, plugin does not delete its comments, this task is delegated to Stash, Indeed, Stash automatically removes a comment if the line is modified. But in this case, like code does not moved, I do confirm, comments will not be deleted...

This ticket is relevant but we need to take care not to impact plugin performance.

**Comment by juherr** [comment]
And why not having an option (disabled by default) where the description will give the potential perfomance issue?

**Comment by acopet** [comment]
**Pull-request #29 submitted.**

Through a new option, the plugin will be able to delete all comments submitted during previous SQ analysis. This reset is the initial action run by the plugin and it deletes only comments submitted by the SonarQube user.

Strong effort has been done to optimize the reset not to impact to much plugin performance.

**Comment by juherr** [comment]
:+1:

**Comment by acopet** [comment]
**Feature available on master branch and will be release with plugin version 1.1.0.**
