### ISSUE TITLE
Issues reported on all lines of the file not just commits

### ISSUE THREAD

**Issue by kalpsraju** [AmadeusITGroup/sonar-stash#142]
Using sonarqube 6.2 with sonar-scanner and bitbucket 4.14.5. Currently the plugin opens tasks or report error on all the lines which has error. Is it possible to just show the bugs for the code changes/commits involved in the pull request

**Comment by kalpsraju** [comment]
FYI I have "Include Vicinity Issues Range" set to 0 and "Include Existing Issues" turned off.

**Comment by kalpsraju** [comment]
<img width="1440" alt="screen shot 2017-08-09 at 5 16 54 pm" src="https://user-images.githubusercontent.com/1628344/29149100-a25fc204-7d26-11e7-9247-e5051c8bd4dd.png">

**Comment by t-8ch** [comment]
Hi @kalpsraju Could you tell me the plugin version you are using, so I can try to reproduce this?

**Comment by kalpsraju** [comment]
I built from latest source as of yesterday.

**Comment by t-8ch** [comment]
@kalpsraju I can't really reproduce this.
Could you check the file in question in the sonarqube UI and see which issues are reported there?

**Comment by haedri** [comment]
Sorry I don't have time to create a pull request or anything, so I'll just drop here what I did to solve a similar problem I had.
By default stash api returns lines around the diff when asking the pull request diff, so I ended up using the contextLines parameter to avoid getting these lines (https://developer.atlassian.com/static/rest/stash/3.11.6/stash-rest.html#idp2278992)
In StashClient.java I changed the variable API_ONE_PR_DIFF by adding the correct parameter
API_ONE_PR_DIFF = API_ONE_PR + "/diff?withComments=true&contextLines=1";

So now I just get the diff with one line above/below, which is a lot better

Hope it helps

**Comment by t-8ch** [comment]
@kalpsraju : Could you elaborate if the the issues that are reported are new (to SonarQube) or not?

**Comment by kalpsraju** [comment]
Thanks for responding, I am running sonar-scanner with "issues" mode, so its not publishing any results to sonarqube.

In order to repro, hereis my file content. 

class helloworld{

	public static void main(String[] args){
		System.out.println();
                public final int CACHE_REFRESH_SUCCESS = 0;
		try {
		} catch(Exception e) {
		}	 
		
	}
}


Please try to add a line with vulnerability or an exisitng line, then run the analysis.

I am using the following command to run analysis.

sonar-scanner -Dsonar.analysis.mode=issues  -Dsonar.stash.notification=true -Dsonar.stash.project=<stashprjname> -Dsonar.stash.repository=<stashreponame> -Dsonar.stash.pullrequest.id=30

**Comment by chiranjeevi** [comment]
Even I see similar issue, the sonar analysis are not happening on changed/committed code, It is applying across the entire code base, which is not a good sign for developer to look into and fix the issue
I have tried it with latest release 1.3.0.
Let me know if it is fixed in any other commit, so that i can pull the plugin code and build it

**Comment by t-8ch** [comment]
@chiranjeevi are you also on SQ 6.2?

**Comment by t-8ch** [comment]
The logic should [exclude issues that are not marked as new in SQ.](https://github.com/AmadeusITGroup/sonar-stash/blob/8f33097f80da8eb0996c8f482c99f372bbc19a86/src/main/java/org/sonar/plugins/stash/issue/collector/SonarQubeCollector.java#L39)
Either this logic is wrong or the value of `Issue.isNew()` returned by SQ is wrong.

Could you confirm that you are also running the sonarqube analysis on the main development branch of your repository? (Not in `issues mode`).

**Comment by chiranjeevi** [comment]
Hi
I'm running the sonar scanner on preview mode and my SQ version is 5.6.6

**Comment by t-8ch** [comment]
Ok, but in addition to running the preview mode on PRs you should also run the normal mode on your man development branch.

**Comment by kalpsraju** [comment]
i am merging feature branch to master, so by development branch you mean feature or master?

**Comment by t-8ch** [comment]
master

**Comment by kalpsraju** [comment]
thanks for quick reply. Will try,

**Comment by sprasadk** [comment]
Hi @t-8ch ,

Have tried running sonar-scanner in normal mode on the destination branch (i.e., master as you said earlier) and then tried running the sonar-scanner in issues ( and preview) mode on the source branch (i.e., feature) on PR. But it does the same (it opens tasks or reports errors on all the lines having error  but we need to report only to the changes/commits respective to the PR).

By the way, I belong to the same team of kalpsraju.

**Comment by t-8ch** [comment]
@kalpsraju @sprasadk,

can you also have the sonar-scanner generate a html report? (`sonar.issuesReport.html.enable=true`).
If the html report is correct and sonar-stash is not then we can investigate this in the scope of sonar-stash.

**Comment by sprasadk** [comment]
@t-8ch 

Thank you for your response! 

We have tried it and it worked in the way we are expecting. 

But, recently there was an update in Sonar java plugin (we found this on 08/16/2017) from which, it is expecting a value for this property "sonar.java.binaries" for which we had to compile the code at least once and provide the target folder path.

So, our question is, being it a static analysis it is still asking for the compiled files?

**Comment by t-8ch** [comment]
@sprasadk 
what do you mean with "it worked in the way we are expecting"?
Did the html report (of the same preview run as sonar-stash) show different issues than sonar-stash?

I am not really familiar with the sonar java plugin, but some analyzers indeed want access to the built files, probably to reuse information to compiler compiled into them.
