### ISSUE TITLE
Minimal required permission for the user to be able to decorate the PR

### ISSUE THREAD

**Issue by racodond** [AmadeusITGroup/sonar-stash#15]
Hi,

> User needs to have expected permissions to access to the repository

Would it be possible to update the README file to clearly state what the minimal required permission (READ?) is for the user to be able to decorate the PR?

Thank you

Regards,

David

**Comment by acopet** [comment]
As mentioned within [Stash Rest API documentation](https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1448560), user needs to have REPO_READ permission.
> The authenticated user must have REPO_READ permission for the repository that this pull request targets to call this resource.

This mention is going to be added into README file.

Thanks for this feedback David!
