### ISSUE TITLE
"does not belong to diff view" issue prevails in Gradle build

### ISSUE THREAD

**Issue by hosszubalazs** [AmadeusITGroup/sonar-stash#150]
Using plugin version 1.3 , Sonar version 6.5
Analysing the project like suggested on the README page. The summary commented is added to the PR, but not the individual comments.
Adding -Dsonar.stash.repository.root="$PWD" to the command line does not change the behaviour, still no issue specific comments.

Sonar is started from the git root folder, and contains multiple submodules.

**Comment by t-8ch** [comment]
Hi @hosszubalazs ,

Can you post an example of the Log output for "does not belong to diff view"?
I would like to see the path mentioned in the log output and if it matches the path in the repository.

**Comment by hosszubalazs** [comment]
Hi @t-8ch,
Thanks for your support!

My structure:
project-root/
- my-favourite-subproject
- another-subproject
- and-another-subproject

```
Comment "IdentifierA" cannot be pushed to Stash like it does not belong to diff view - my-favourite-subproject/src/main/java/path/FaultyCode.java (line: 39)
Comment "IdentifierB" cannot be pushed to Stash like it does not belong to diff view - my-favourite-subproject/src/main/java/path/FaultyCode.java (line: 39)
```

I have the Sonar Gradle plugin applied on the root build.gradle, this is where I start sonar with the sonarqube command. $PWD is "/local/absolute/path/to/project-root". The latest Gradle plugin is used.

Best,
hosszub

**Comment by t-8ch** [comment]
@hosszubalazs ,

is `my-favourite-subproject/src/main/java/path/FaultyCode.java` the actual path on your filesystem?
And is it included in the diff of the PR?

**Comment by t-8ch** [comment]
Can you also show me how you run the sonar scanner?
"$PWD" assumes that sonar-scanner is executed from a shell and may not work with the gradle plugin

**Comment by hosszubalazs** [comment]
Hey @t-8ch!

"my-favourite-subproject/src/main/java/path/FaultyCode.java" -> This is the relative path of my file under project root. The full path would be : 
`"/local/absolute/path/to/project-root/my-favourite-subproject/src/main/java/path/FaultyCode.java".`

My Sonar command is.
`gw sonarqube --info -Dsonar.host.url=... -Dsonar.analysis.mode=preview -Dsonar.stash.notification=true -Dsonar.stash.project=.. -Dsonar.stash.repository=... -Dsonar.stash.pullrequest.id=... -Dsonar.stash.url=... -Dsonar.stash.timeout=100000   -Dsonar.stash.repository.root="$PWD"`

The summary comment is added, so atuhentication is fine. I also tried sonar.stash.repository.root="/local/absolute/path/to/project-root", same results.

**Comment by t-8ch** [comment]
Can you confirm that `/local/absolute/path/to/project-root/my-favourite-subproject/src/main/java/path/FaultyCode.java` is both the correct path in your local repository and in bitbucket?

**Comment by hosszubalazs** [comment]
Dear @t-8ch!

"is both the correct path in your local repository and in bitbucket?" At the time of opening the PR, they were different. Through changes the paths have been updated, but did not resolve the issue.
However, abandoning the original the PR, and opening a new one while making sure the path are correct in both places results in correct behaviour, without the need for stash.respository.root to be specified.

Thanks for all your support! The issue is resolved.
