### ISSUE TITLE
Issue list not showing all the issues

### ISSUE THREAD

**Issue by sidd9433** [AmadeusITGroup/sonar-stash#154]
The total number of issues ate not matching in issue list.

![image](https://user-images.githubusercontent.com/20203936/31004729-e8bcc25a-a4f5-11e7-930f-36e18318e20d.png)

The total number is the correct count. I have sonar-stash 1.3.0

Any solution?

**Comment by t-8ch** [comment]
Hi @sidd9433 ,

this is intentional. The issue list only show each issue once.
