### ISSUE TITLE
The plugin should not update a message when its content doesn't change

### ISSUE THREAD

**Issue by juherr** [AmadeusITGroup/sonar-stash#16]
It seems the plugin is removing+creating or updating a message after every sonar run.
That's mean the email notifications will always contains the same issues if they were not resolved => lot of noise.

The idea is to not update a message if the content will be the same.

**Comment by acopet** [comment]
Hello Julien,
First of all, sorry for the delay to answer to this comment. About this issue, this feature is already implemented: plugin does not push an issue if this issue if already attached to a line.

From src/main/java/org/sonar/plugins/stash/StashRequestFacade.java:

 ```java
// if comment not already pushed to Stash
if ((comments != null) &&
    (comments.contains(MarkdownPrinter.printIssueMarkdown(issue, sonarQubeURL), issue.getPath(), issue.getLine()))) {
     LOGGER.debug("Comment \"{}\" already pushed on file {} ({})", issue.getRule(), issue.getPath(), issue.getLine());
} else {
        ...
```

**Comment by juherr** [comment]
Ok! I will check it again.

**Comment by juherr** [comment]
Ok, I confirm: comments are not updated but a new summary is writen even there is no new comments what disturbed me.
