### ISSUE TITLE
analyse only the diff in pull request

### ISSUE THREAD

**Issue by appleajay** [AmadeusITGroup/sonar-stash#165]
Is there a way/option from which I can enable this plugin to analyse only the diff and show the results of that only( not the whole project). 
Thanks in advance

**Comment by t-8ch** [comment]
Hi @appleajay,
The only way this plugin can work reliably is by having a baseline scan of the main development branch.
Then you execute sonar in preview/issues mode with this plugin on a PR branch to get the differences between the PR and the main development branch.
