### ISSUE TITLE
Checking out wrong Revision on PR

### ISSUE THREAD

**Issue by hax0rdlux3** [AmadeusITGroup/sonar-stash#167]
Hello,

 In certain circumstances it appears the git checkout command pulls the wrong Revision for certain users:

> git.exe tag -l # timeout=10
Checking out Revision revID
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f revID
Commit message: "make one change"
 > git.exe rev-list # timeout=10

the Revision that correlates to the PR is not what is being pulled for analysis. 

thx

**Comment by t-8ch** [comment]
This plugin does not perform any git operations. The problem has to be elsewhere.
