### ISSUE TITLE
Sonar 6.7 LTS support

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#168]
Hi,

Is there any plan to support 6.7 LTS sonar version?

Regards,
Oleg

**Comment by t-8ch** [comment]
Of course!
So far I did not perform any tests.
If you encounter any issues please report them.
(If it works smoothly feel free to also report it).

I'll have a look at the changelogs.

**Comment by kingoleg** [comment]
Hi,

It works on my sandbox with 1 change: 

-Dsonar.analysis.mode=issues

And without coverage evolution :(

**Comment by t-8ch** [comment]
@kingoleg The coverage feature works for me.
FYI The coverage functionality has been split into its own plugin: 
https://github.com/AmadeusITGroup/sonar-coverage-evolution
