### ISSUE TITLE
Allow skipping and/or personalization of the overview comment

### ISSUE THREAD

**Issue by lared** [AmadeusITGroup/sonar-stash#170]
When pushing often, the overview comments seem to add little value over the actual issue comments. This is especially annoying when you don't care much about the type of reported issues (as you expect all of them to be addressed in one way or the other anyway). 

How would you feel about adding a property which allows to opt-out of the overview comments, or maybe allowing some customization (so that theses comments would be less prominent - a simple template would likely be sufficient)?

**Comment by t-8ch** [comment]
@lared `sonar.stash.include.overview` allows you to skip the report completely, is this acceptable?

**Comment by lared** [comment]
@t-8ch Yes, thank you! I've missed it completely. Sorry for that, it's been a long week already and it's only Wednesday.
