### ISSUE TITLE
Property stash.include.existing.issues ignored?

### ISSUE THREAD

**Issue by TobiasJanz** [AmadeusITGroup/sonar-stash#173]
Hello,

I try to have a clean Codebase and no PullRequest should be merged as long as there are Issues from SonarQube. In my case it doesn't matter if they are old or new ones.
So I did set the property stash.include.existing.issues=true but I still get no Issues in the Overview-Comment. There are some issues i can see in SonarQube.

Thanks for any Help.

Configuration:
Bitbucket Server 5.5.1
Jenkins 2.89.1
Sonar 6.7
Sonar-Stash 1.3.0

Call:
./gradlew sonarqube -Dsonar.projectVersion=#59 -Dsonar.stash.url=URL -Dsonar.stash.reviewer.approval=false -Dsonar.stash.include.existing.issues=true -Dsonar.stash.include.overview=true -Dsonar.stash.notification=true -Dsonar.stash.project=PROJECT -Dsonar.stash.pullrequest.id=23 -Dsonar.stash.login=USER -Dsonar.stash.password=PASSWORD -Dsonar.stash.repository=REPOSITORY -Dsonar.analysis.mode=preview

**Comment by t-8ch** [comment]
Hi @TobiasJanz,
this feature was introduced after 1.3.0 was released.
I fear you would have to use the master branch or wait for 1.4.0.

**Comment by TobiasJanz** [comment]
Hi t-8ch,
thanks for your quick answer.
Thats good to know. Is there allready a timeline for 1.4.0?

**Comment by t-8ch** [comment]
Not really, but I think I will try to wrap some current issues and finalize it afterwards.

**Comment by TobiasJanz** [comment]
Thank you sounds good.
