### ISSUE TITLE
Pull Request doesn't show the issue 

### ISSUE THREAD

**Issue by ahmedelkoush** [AmadeusITGroup/sonar-stash#177]
Hi Dear,

KIndly i follow the steps but  i think something going wrong with me i couldnt catch the issue would you Please help me?

The following is properties i reflect on sonar-scanner.properties 
sonar.projectKey=TRAFFIC
sonar.projectName=TRAFFIC
sonar.projectVersion=1.0
sonar.stash.password=(i put my bitbucket password)
analysis.mode=issues
stash.notification=true
stash.project=https://bitbucket.org/idealsoft
stash.repository=https://bitbucket.org/idealsoft/trf
pullrequest.id=1878
stash.password=(i put my bitbucket password)

**Comment by t-8ch** [comment]
Hi @ahmedelkoush,

This plugin can only talk to Bitbucket Server, not Bitbucket cloud.
(At least until #66 is resolved)
