### ISSUE TITLE
Ignore false positive, and won't fix from overview comment

### ISSUE THREAD

**Issue by datasmurfen** [AmadeusITGroup/sonar-stash#180]
Hello, 

Would be great if you could ignore false positive, and won't fix issues from being analyzed, and listed in overview comment.   

SonarQube version: 7.1

**Comment by t-8ch** [comment]
By default only new issues should be reported, so this would be implicitly true.
Are you thinking about the case, when existing issues are reported?

**Comment by t-8ch** [comment]
Also the information we have about an issue is essentially documented here:
http://javadocs.sonarsource.org/6.7/apidocs/org/sonar/api/batch/postjob/issue/PostJobIssue.html

**Comment by datasmurfen** [comment]
aaaa yea my mistake  :) 👍
