### ISSUE TITLE
Cannot approve Pull Request

### ISSUE THREAD

**Issue by abialas** [AmadeusITGroup/sonar-stash#187]
I want sonar user to approve the pull request in case there are no new blocker issues. I am passing setting via command line. However, all the time I see in logs that NOT APPROVED by user X. The parameters I am passing:
-Dsonar.stash.reviewer.approval=true
-Dsonar.stash.reviewer.approval.severity.threshold=BLOCKER

I am sure there are no new BLOCKER issues (I can see on the Pull Request tab). What else should I set?

**Comment by t-8ch** [comment]
Hi @abialas Can you provide the following information:
* Version of SonarQube you are using
* Version of sonar-stash you are using
* Complete commandline of your execution
* Log of your execution (Please note, that debug logs will include your user credentials in the http logging)
  A normal level log should be enough

**Comment by abialas** [comment]
We are using SonarQube 6.7.2. I cannot check now the version of Sonar Stash. The command we are using:

bash gradlew sonarqube 
	-Dsonar.analysis.mode=preview 
	-Dsonar.stash.notification=true 
	-Dsonar.stash.include.overview=false 
	-Dsonar.stash.pullrequest.id=73 
	-Dsonar.stash.comments.reset=true 
	-Dsonar.stash.reviewer.approval=true 
	-Dsonar.stash.reviewer.approval.severity.threshold=BLOCKER

**Comment by t-8ch** [comment]
The version of sonar-stash is printed during the execution.
Please also provide me with a build log.
The best approach would be to test it with a brand new simple project.

**Comment by abialas** [comment]
The version of Stash is 1.3.0. I will try to create a simple small project and execute the analysis on it. However, I discovered that in case there is no new issue in PR then it can be approved. Seems the setting -Dsonar.stash.reviewer.approval.severity.threshold=BLOCKER is not taken into consideration.

**Comment by t-8ch** [comment]
The threshold was introduced in 1.4.0

**Comment by abialas** [comment]
Is there already a final version of 1.4.0 or just a SNAPSHOT?

**Comment by t-8ch** [comment]
https://github.com/AmadeusITGroup/sonar-stash/releases/tag/1.4.0
