### ISSUE TITLE
Make summary comment optional

### ISSUE THREAD

**Issue by christiangalsterer** [AmadeusITGroup/sonar-stash#19]
The summary comment is taking quite some space. It would be nice to make it configurable if the summery comment shall be added or not.

**Comment by christiangalsterer** [comment]
PR #20 available. Please note that it is passed on #17.

**Comment by christiangalsterer** [comment]
I updated the PR to remove the code for configuring the password for Stash as discussed in #17.

**Comment by christiangalsterer** [comment]
Hi,
any update on this? What are your views/plans for a next release and would it be available to integrate the related PR?

**Comment by acopet** [comment]
Hello Christian,

We are finalizing the integration of issue #7. When ended, we have planned to deliver, probably at the end of this month, the release 1.1.0 which will also contain issues #11 and #14. Your contribution is still a candidate but for the next release 1.2.0.

Antoine

**Comment by ghenzler** [comment]
It has not made it to 1.2.0, it would be great to see this in the next release.
