### ISSUE TITLE
New Feature suggestion - Include code coverage, and alert if quality gate fail on Pull request

### ISSUE THREAD

**Issue by datasmurfen** [AmadeusITGroup/sonar-stash#192]
New Feature suggestion - Include code coverage, and alert if quality gate fail on pull request. 

This is something I miss - today we use: https://github.com/kogitant/sonar-slack-notifier-plugin , but would be better to have this in one place.

**Comment by t-8ch** [comment]
Hi @datasmurfen,
Can you elaborate about "Include Code coverage"?
The problem with the quality gate is that is executed asynchronously and has not yet finished when sonar-stash is running. (This is also tracked in #95)

**Comment by t-8ch** [comment]
Also the quality gate is not run on preview runs (See #95)

**Comment by t-8ch** [comment]
Well, it could be done, but it would be really confusing. I am strongly -1 on it.

**Comment by datasmurfen** [comment]
Yea I agree, it would be very confusing.

**Comment by t-8ch** [comment]
Could you elaborate on the coverage you want to see?
There is the [coverage evolution plugin](https://github.com/AmadeusITGroup/sonar-coverage-evolution).
It has a few caveats that are documented its README

**Comment by datasmurfen** [comment]
I think it would been great to see if your pull request brakes/fix the current quality gate with an comment on what you break. 

Must Have
*  Coverage on New Code is less then X %
And alert if that is less then quality gate with an comment in the PR. 

Could have: 
* Duplicated Lines on New Code is less
* Maintainability Rating on New Code
* Reliability Rating on New Code
* Security Rating
Security Rating on New Code

**Comment by t-8ch** [comment]
Ok, so it's also tied to the quality gate.
As there is no quality gate available there is not much we can do.
This will probably happen at all, because SonarSource is promoting their own (closed, paid) branch and pull request solution.
