### ISSUE TITLE
Issue comment on the wrong line

### ISSUE THREAD

**Issue by adhikasp** [AmadeusITGroup/sonar-stash#194]
I was trying to use sonar-stash plugin, but found that the sonar bot was commenting the pull request on the wrong line.

![image](https://user-images.githubusercontent.com/6151302/48815310-ac70e500-ed70-11e8-9045-d7ebc8bd8f12.png)

As you can see, the comment was on line no 106 of **old diff** instead of line 106 **new diff**.

Version used:
- sonar-stash 1.5
- sonar 6.7.3
- bitbucket 5.15.0

**Comment by adhikasp** [comment]
I did a little debugging and found out that:

- I enable vicinity with value `sonar.stash.include.vicinity.issues.range = 5`
- `includeVicinityIssuesForDiff(StashDiff diff, long destination, int range)` seems buggy because the comment got matched with "vicinity" instead of exact line.

After I set vicinity range as 0, it post at the addition diff correctly

**Comment by t-8ch** [comment]
Hi @adhikasp , thanks for the report!
Could you provide me with the raw JSON response from bitbucket?
(`/rest/api/1.0/projects/xxx/repos/xxx/pull-requests/xxx/diff?withComments=true`, replace `xxx` with the correct values).
Please obfuscate all names you don't want to be public.
This will make it much easier to test and fix the issue.

**Comment by adhikasp** [comment]
@t-8ch sure, here is the json dump https://gist.github.com/adhikasp/1920791cc2436af2f8145863861f9b0e

I was messing around with the code, and this modification fix the problem
```java
public IssueType getType(String path, long destination, int vicinityRange) {
    IssueType tmpType = null;
    for (StashDiff diff : diffs) {
      if (Objects.equals(diff.getPath(), path)) {
        // Line 0 never belongs to Stash Diff view.
        // It is a global comment with a type set to CONTEXT.
        if (destination == 0) {
          return IssueType.CONTEXT;
        } else if (destination == diff.getDestination()) {
          return diff.getType();
        } else if (includeVicinityIssuesForDiff(diff, destination, vicinityRange)) {
          tmpType = diff.getType();
        }
      }
    }
    return tmpType;
  }
```

It seems that `sonar-stash` couldn't differentiate between issues that was raised from code change and issues from existing code, and thus pick the wrong `lineType`. In this particular case, `sonar-stash` pick the `CONTEXT` diff because it contains the problematic line in its vicinity and it appear first in the `StashDiff` iteration. This hack works but the logic seems unreliable for other conditions.

**Comment by t-8ch** [comment]
Could you also provide the line number, sonarqube thinks this issue belongs to?
(Try to put a print into the `StashIssueReportingPostJob`)

**Comment by adhikasp** [comment]
@t-8ch here it is
```
[INFO] Issue key 01673981387EDCCDB0, ruleKey ModifiersOrderCheck, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 56
[INFO] Issue key 01673981387EDCCDB1, ruleKey S106, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 109
[INFO] Issue key 01673981387EDCCDB2, ruleKey S106, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 120
[INFO] Issue key 01673981387EDCCDB3, ruleKey S2583, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 108
[INFO] Issue key 01673981387EDCCDB4, ruleKey S1481, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 106
[INFO] Issue key 01673981387EDCCDB5, ruleKey S1185, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 207
[INFO] Issue key 01673981387EDCCDB6, ruleKey S00117, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 106
[INFO] Issue key 01673981387EDCCDB7, ruleKey S00117, componentKey com.gdn.package:module-api-client:src/main/java/com/gdn/package/module/client/ModuleClient.java, line 119
```

**Comment by t-8ch** [comment]
I am building a complete test case, but the file in question from the log is
`ModuleClient.java` while in the JSON it is `aModuleClient.java`.
