### ISSUE TITLE
Support to report existing issues and vicinity issues

### ISSUE THREAD

**Issue by christiangalsterer** [AmadeusITGroup/sonar-stash#23]
Hi,

first of all thanks for the great plugin. We use it since several week and it is just great.
As we don't want to see only the new issues found during an incremental analysis of a pull request, but also existing issue of modified code and issue which are in the vicinity of the modified code I have implemented two new features:
1. Report Existing Issues
   Setting this property to true the plugin will also report any existing issues in the modified code to Stash/Bitbucket as a comment.
2. Similar to the first feature this property set to true will also report any issues which are in the vicinity to the modified code of the pull request. Vicinity is hereby determined by the fact that Stash/Bitbucket only allows to set comments on the pull request diff view +/- 10 lines around the modified code. This is respected by the plugin and reports only issues which are in this range.

Both properties are set to false to keep the existing behaviour. 
We have this running already for a couple of days and the feedback from the developers are very positive as they can also quickly fix already existing issue and/or vicinity issues as they are anyway touch the code (Boy Scout Rule).

Hope you find this useful as well and accept my my pr.

**Comment by acopet** [comment]
Hello Christian,

Thank you very much for this new contribution: we will deploy these new features and provide a feedback quickly!

**Comment by christiangalsterer** [comment]
Did you had a chance to look at the pull request? Please let me know if you have any questions/comments.

**Comment by acopet** [comment]
Unfortunately not yet...
But we will have a look quickly, I hope before end of this week.

**Comment by nvillard** [comment]
Hello @christiangalsterer 
I will have a look at your contribution in the week.
I am not sure this feature is something we really want since the objective of the plugin is to give you direct feedback about your new code only. That's why all the plugin is based on the new violations.
However, i can understand in some situations the interest of having this feature (in the case you want to improve quality on legacy code for example), and i think in this case it can make sense, but for sure, this has to be configurable.
I let you know since i have a look at your contribution.

**Comment by christiangalsterer** [comment]
Hi @nvillard ,
I made the new features already configurable and the default is that they are switched off. By this the current behaviour of the plugin is not changed and doesn't interfere.

**Comment by christiangalsterer** [comment]
Hi @nvillard,

as some time has passed did you had a chance to look into this? What are the plans for a next release?

**Comment by christiangalsterer** [comment]
As more then a year has pasted I was wondering if there is every a change to get this approved or if it makes more sense to fork the project...

**Comment by jannylund** [comment]
I agree. Waiting for some other PR's to merge, and this one would also make a lot of sense to me. I guess forking would be the proper way to go, eventually.

**Comment by t-8ch** [comment]
#97 has been merged.
