### ISSUE TITLE
Rename plugin as SonarQube Stash Plugin

### ISSUE THREAD

**Issue by acopet** [AmadeusITGroup/sonar-stash#3]
After discussion with SonarSource, rename the plugin as "SonarQube Stash Plugin" to match SonarQube convention. This renaming will be done inside ReadMe.md.

**Comment by localgod** [comment]
"SonarQube BitBucket Plugin" might be more appropriate as Stash is no longer a product.

**Comment by acopet** [comment]
Plugin will be renamed as "SonarQube Stash (BitBucket) plugin".

Stash renaming has been done with version 4.0. Like plugin supports for moment Stash version 3.x, we will fully rename the plugin when issue #4 will be implemented.
