### ISSUE TITLE
Update README file as sonar.analysis.mode=incremental is no longer available in SonarQube 5.2+

### ISSUE THREAD

**Issue by racodond** [AmadeusITGroup/sonar-stash#31]
See https://github.com/racodond/sonar-stash/commit/7bb3b9d6b53359c9c6a4ce367986e6dde9b46cbb

**Comment by acopet** [comment]
Thanks David!

To modify as well: Prerequisite from README:

#### Prerequisites

- Git client to checkout the code
- Maven 3.0.5
- JDK 1.7
- **SonarQube 4.5.4 (LTS)**
- Stash (BitBucket) 3.x

**Comment by re-schneider** [comment]
Addressed by Pull-request #55
