### ISSUE TITLE
Factorize the code

### ISSUE THREAD

**Issue by nvillard** [AmadeusITGroup/sonar-stash#32]
Some methods are a bit too big to have clear understanding in one shot. Obejctive of this issue is to provide a small factorization of the code in order to:
- reduce duplicate
- improve readability
- ease new improvements

**Comment by re-schneider** [comment]
Latest Sonar report is only listing 2 blocks duplicated: https://sonarqube.com/overview?id=org.sonar%3Asonar-stash-plugin

This is not a critical situation and it may get addressed during upcoming new features release.
