### ISSUE TITLE
Comment cannot be pushed to Stash like it does not belong to diff view (method too large)

### ISSUE THREAD

**Issue by jonathan-top** [AmadeusITGroup/sonar-stash#34]
I have a pull request in which two method bodies infringe the method cyclomatic complexity rule.
The method bodies are pretty large (>80 lines), and the diff is an addition at the end of the method.
Because the diff view doesn't show the first line of the method (that would be because of the size), the plugin gives a "Comment cannot be pushed to Stash like it does not belong to diff view (method too large)" warning.
Could we find a way around this?

**Comment by nvillard** [comment]
Hi,

Could you please provide more details about the class and the method.
I am working on a "method length reduction" feature, mainly on StashCollector and StashIssueReportingPostJob.

**Comment by t-8ch** [comment]
#135 describes this problem better
