### ISSUE TITLE
Received 404 with message Not Found

### ISSUE THREAD

**Issue by RaviFIS** [AmadeusITGroup/sonar-stash#35]
Hello 

i am trying to setup this plugin in our development environment. I am able to complete the analysis but in the it throws me the following error

Unable to get SonarQube reviewer from Stash: Unable to retrieve user.
process stopped: no SonarQube reviewer identified to publish to Stash the SQ analysis

The required user that has been setup has both read and write permission on the repository.  I tried to look through document but was unable to get any answer.

Appreciate any inputs.

Thanks
Ravi.

**Comment by acopet** [comment]
Hello Ravi,

Could you please make a run in debug mode "-Dsonar.verbose" and share the log?

I confirm your user needs **REPO_WRITE & REPO_READ** permission fro the repositories (documented in "Configuration on SonarQube server" chapter in README file). And the user needs to be declared from General settings screen (option **Stash base User**).

Cheers,
Antoine

**Comment by RaviFIS** [comment]
Here is the log  Stash says it is unable to retrieve the user.  I confirmed that user is there. please note we are integrated to crowd and user is defined in crowd and that user has got read and write to the git repository in question.

[DEBUG] [16:39:13.194] Adding key: http://vcmlstashpoc.atldev.com:7990 for channel [id: 0x0e27d6cc, /10.135.129.91:60833 => vcmlstashpoc.atldev.com/10.135.138.41:7990]
build	03-Feb-2016 16:39:13	[ERROR] [16:39:13.225] Unable to get SonarQube reviewer from Stash: Unable to retrieve user bam-build. Received 404 with message Not Found.
build	03-Feb-2016 16:39:13	[DEBUG] [16:39:13.241] Exception stack trace
build	03-Feb-2016 16:39:13	org.sonar.plugins.stash.exceptions.StashClientException: Unable to retrieve user bam-build. Received 404 with message Not Found.
build	03-Feb-2016 16:39:13		at org.sonar.plugins.stash.client.StashClient.getUser(StashClient.java:227) ~[sonar-stash-plugin-1.1.0.FIS-SNAPSHOT.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.plugins.stash.StashRequestFacade.getSonarQubeReviewer(StashRequestFacade.java:252) ~[sonar-stash-plugin-1.1.0.FIS-SNAPSHOT.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:55) [sonar-stash-plugin-1.1.0.FIS-SNAPSHOT.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:72) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:61) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:132) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67) [sonar-batch-maven-compat-4.5.6.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.runner.batch.BatchIsolatedLauncher.executeOldVersion(BatchIsolatedLauncher.java:86) [sonar-runner-batch4318560145910671508.jar:na]
build	03-Feb-2016 16:39:13		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61) [sonar-runner-api-2.5.1.jar:na]
build	03-Feb-2016 16:39:13		at com.sun.proxy.$Proxy21.executeOldVersion(Unknown Source) [na:na]
build	03-Feb-2016 16:39:13		at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:283) [sonar-runner-api-2.5.1.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165) [sonar-runner-api-2.5.1.jar:na]
build	03-Feb-2016 16:39:13		at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152) [sonar-runner-api-2.5.1.jar:na]
build	03-Feb-2016 16:39:13		at org.sonarsource.scanner.maven.bootstrap.RunnerBootstrapper.execute(RunnerBootstrapper.java:78) [sonar-maven-plugin-3.0.1.jar:na]
build	03-Feb-2016 16:39:13		at org.sonarsource.scanner.maven.SonarQubeMojo.execute(SonarQubeMojo.java:112) [sonar-maven-plugin-3.0.1.jar:na]
build	03-Feb-2016 16:39:13		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155) [maven-core-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584) [maven-embedder-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216) [maven-embedder-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at org.apache.maven.cli.MavenCli.main(MavenCli.java:160) [maven-embedder-3.2.5.jar:3.2.5]
build	03-Feb-2016 16:39:13		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
build	03-Feb-2016 16:39:13		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.2.jar:na]
build	03-Feb-2016 16:39:13		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.2.jar:na]
build	03-Feb-2016 16:39:13		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.2.jar:na]
build	03-Feb-2016 16:39:13		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.2.jar:na]
build	03-Feb-2016 16:39:13	[ERROR] [16:39:13.241] Process stopped: no SonarQube reviewer identified to publish to Stash the SQ analysis

Thanks
Ravi.

**Comment by RaviFIS** [comment]
I think i found the answer.  Instead of using existing service account created a new service account called sonarqube and added it to the group that was recognized by stash. Synced up stash with crowd user directories  also added the service account with read access to the required git repository. After this  things seems to work at the moment. 

Can the service account name be anything ? or does it have to be called "sonarqube" ?

Thanks
Ravi.

**Comment by acopet** [comment]
You can use the name you want. This user just needs to be declared from General Setting page in SonarQube server (field **Stash base User**) and, of course, in Stash with READ / WRITE access on expected repositories. SonarQube Stash plugin will push all the issues to Stash through this user.

**Comment by salustudy** [comment]
Hi Acopet ,
i have same issue . i tired with two user one having only read repo permission and aonther has both read and write permission ,each time i am getting same error .
ERROR] [10:05:17.241] Unable to get SonarQube reviewer from Stash: Unable to retrieve user XXXX. Received 404 with message Not Found.
[ERROR] [10:05:17.241] Process stopped: no SonarQube reviewer identified to publish to Stash the SQ analysis . 
Please help me out 
Cheers
Salamat

**Comment by acopet** [comment]
@RaviFIS, did you manage to figure out your issue?

**Comment by RaviFIS** [comment]
Yes since we are using crowd group i had to add the user under crowd group after which i was able make the review work.

Thanks
Ravi.
