### ISSUE TITLE
will sonar-stash plugin work with Stash v2.10.2

### ISSUE THREAD

**Issue by salustudy** [AmadeusITGroup/sonar-stash#36]
i have Stash v2.10.2, i have configured sonar-stash plugin with sonar 4.5.6,plugin added successfully,but sonar issues are not showing in pull request?will sonar-stash plugin work for Stash v2.10.2 ?

Cheers
Salamat

**Comment by acopet** [comment]
Hello @salustudy,

Is this issue linked to #37?

SonarQube Stash plugin supports officially Stash version 3.x and we never made any tests with version 2.x. However, plugin is based on this version of the [Stash Rest api](https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html): if your Stash 2.10 is compatible with this Rest api, plugin should works.



Cheers,
Antoine

**Comment by acopet** [comment]
**Close this issue as there is no more feedback since 3 months.**
Feel free to reopen this issue if relevant.

Cheers,
Antoine
