### ISSUE TITLE
Bitbucket 4.1.0 Compatibility

### ISSUE THREAD

**Issue by emreyokur** [AmadeusITGroup/sonar-stash#38]
Hello @acopet 

Kudos to you for seeing the need for sonar issues in pull request diff view.  

We are using Atlassian Bitbucket 4.1.0 and SonarQube 5.2, do you have any planned release date for making the plugin compatible for these versions?

**Comment by acopet** [comment]
Hello @emreyokur,

Plugin should work with SonarQube 5.2. You just need to replace analysis mode from **incremental** to **preview** (issue #31). 

About compatibility with Bitbucket 4.x, did you try to run the plugin with version 4.1.0? Plugin pushes SonarQube issues through this [Rest API](https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html): I am not sure there is many changes on this API and plugin would probably works. If not, we have planned to migration at beginning of Q2-2016 (issue #4).

Cheers,
Antoine

**Comment by emreyokur** [comment]
Hello @acopet 

I've built the latest revision and tested the plugin with Bitbucket 4.1.0 and SQ 5.2. It works like a charm. 

Keep up the good work!
Emre
