### ISSUE TITLE
Post job sonar review difference 

### ISSUE THREAD

**Issue by RaviFIS** [AmadeusITGroup/sonar-stash#39]
I am seeing the following message after bamboo completes the build.

New SonarQube issues have been reported to Stash.
17-Feb-2016 10:43:11	[INFO] [10:43:11.410] SonarQube analysis overview has been reported to Stash.

which is fine but  in another build report i see this 

WARN] [21:04:57.132] Too many issues detected (111/100): Issues cannot be displayed in Diff view
16-Feb-2016 21:04:58	[INFO] [21:04:58.319] SonarQube analysis overview has been reported to Stash.

In comparing two pull request one pull request says Sonar did not detect any new issues another pull report actually pulls in all the Critical, high and other details.  

I believe PR needs to show  the list of Critical and high and other good details.  How can we make the plugin work consistently  ?  Is this is a setup issue ?

Thanks
Ravi.

**Comment by RaviFIS** [comment]
Basically we are not able to get the diff view in the sonar review

Thanks
Ravi.

**Comment by acopet** [comment]
Hello @RaviFIS ,

We limit the number of SQ issues pushed to the diff view to 100. So, if your pull-request has reached this threshold, no issues into the diff view, only a summary.
 
This setting can be configured from general settings screen in SonarQube. Just update the following property (below comment extracted from README file):    

> Stash issue threshold (sonar.stash.issue.threshold): To limit the number of issue pushed to Stash.

Cheers,
Antoine
