### ISSUE TITLE
Received 401 with message Unauthorized

### ISSUE THREAD

**Issue by yogeshl5481** [AmadeusITGroup/sonar-stash#40]
I am facing below error while using this plugin 

[ERROR] Unable to get SonarQube reviewer from Stash: Unable to retrieve user <my_user_name>. Received 401 with message Unauthorized.
[DEBUG] Exception stack trace
[ERROR] Process stopped: no SonarQube reviewer identified to publish to Stash the SQ analysis

We are using enterprise version of bitbucket and starting this analysis using maven.

Get request URL :
https://<hostname>/bitbucket/rest/api/1.0/users/<my_user_name>

is this error is because of https rest call? if yes is there any different configuration for https?

Environment Details:
Java 7 jdk1.7.0_55
Sonar Cube 5.3
apache-maven-3.3.3

Maven command:
mvn sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.stash.notification -Dsonar.stash.project="ProjectName" -Dsonar.stash.repository=reponame -Dsonar.stash.pullrequest.id=1 -Dsonar.stash.password=password -Dsonar.stash.login=my_use_name -Dsonar.stash.url=https://<hostname>/bitbucket

**Comment by nvillard** [comment]
Hi @yogeshl5481 ,

This is a Stash issue:
https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp299120
Authentication failed or was not attempted. - Unable to retrieve user . Received 401 with message Unauthorized.

Are you sure your user defined in stash plugin panel has read access (sonarqube in this example)?
<img src="https://github.com/AmadeusITGroup/sonar-stash/raw/master/resources/Sonar-plugin-configuration.PNG" width="200" />

Try also to remove -Dsonar.stash.login attribute in your command line as well.

**Comment by acopet** [comment]
Hello @yogeshl5481,

Any news on this issue?

Cheers,
Antoine

**Comment by yogeshl5481** [comment]
No luck so far. I am suspecting issue is in Single Sign on infrastructure setup in my organisation.
I think you can go ahead and close this issue.
