### ISSUE TITLE
Unable to push SonarQube analysis overview to Stash: Unable to post a comment to <PR>. Received 400 with message Bad Request

### ISSUE THREAD

**Issue by RaviFIS** [AmadeusITGroup/sonar-stash#42]
The automated reviews were working fine until last week.

I confirmed that sonarqube user belongs to correct crowd group , not sure why we are receiving error 400  as shown below

Request DefaultHttpRequest(chunked: false)
build   21-Mar-2016 15:51:43    POST /rest/api/1.0/projects/ABC/repos/abc/pull-requests/45/comments HTTP/1.1
build   21-Mar-2016 15:51:43    Content-Type: application/json
build   21-Mar-2016 15:51:43    Content-Length: 932
build   21-Mar-2016 15:51:43    Connection: keep-alive
build   21-Mar-2016 15:51:43    Host: xxx.xyz.com:7990
build   21-Mar-2016 15:51:43    Authorization: Basic c29uYXJxdWJlOnNvbmFycXViZQ==
build   21-Mar-2016 15:51:43    Accept: _/_
build   21-Mar-2016 15:51:43    User-Agent: AHC/1.0
build   21-Mar-2016 15:51:43  
build   21-Mar-2016 15:51:43    Response DefaultHttpResponse(chunked: true)
build   21-Mar-2016 15:51:43    HTTP/1.1 400 Bad Request
build   21-Mar-2016 15:51:43    Server: Apache-Coyote/1.1
build   21-Mar-2016 15:51:43    X-AREQUESTID: @NRVL0Ux951x13983647x1
build   21-Mar-2016 15:51:43    X-ASEN: SEN-2307067
build   21-Mar-2016 15:51:43    X-AUSERNAME: sonarqube
build   21-Mar-2016 15:51:43    X-AUSERID: 12393
build   21-Mar-2016 15:51:43    Cache-Control: no-cache, no-transform
build   21-Mar-2016 15:51:43    Vary: X-AUSERNAME,Accept-Encoding
build   21-Mar-2016 15:51:43    Transfer-Encoding: chunked
build   21-Mar-2016 15:51:43    Content-Type: application/json;charset=UTF-8
build   21-Mar-2016 15:51:43    X-Content-Type-Options: nosniff
build   21-Mar-2016 15:51:43    Date: Mon, 21 Mar 2016 20:51:23 GMT
build   21-Mar-2016 15:51:43    Connection: close
build   21-Mar-2016 15:51:43  
build   21-Mar-2016 15:51:43    [DEBUG] [15:51:43.013] Closing Channel [id: 0x900d6bde, /10.135.128.209:52404 => xxx.xxx.com/10.135.138.41:7990] 
build   21-Mar-2016 15:51:43    [DEBUG] [15:51:43.013] Channel Closed: [id: 0x900d6bde, /10.135.128.209:52404 :> xxx.xyx.com/1.2.3.4:7990] with attribute INSTANCE
build   21-Mar-2016 15:51:43    [ERROR] [15:51:43.013] Unable to push SonarQube analysis overview to Stash: Unable to post a comment to abc#45. Received 400 with message Bad Request.
build   21-Mar-2016 15:51:43    [DEBUG] [15:51:43.013] Exception stack trace
build   21-Mar-2016 15:51:43    org.sonar.plugins.stash.exceptions.StashClientException: Unable to post a comment to abc#45. Received 400 with message Bad Request.

Thanks
Ravi.

**Comment by nvillard** [comment]
https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1448560

400 (Bad Request) 	One or more of the required parameters or attributes:
    were missing from the request;
    incorrectly formatted; or
    inappropriate in the given context.

I guess there is something wrong with one of the new violation to be pushed as comment. Investigation to be done

**Comment by RaviFIS** [comment]
Yes i understand. But on another project there is only change to a pom file and i was expecting Sonarqube review as no new issues found instead a 400 error is thrown.  Do you see any setup issue ?

Ravi

**Comment by nvillard** [comment]
What can be considered:
- new Stash version
- new SonarQube version
- new violation
- new Quality Gate

**Comment by sparty02** [comment]
@RaviFIS Maybe try turning on [Stash debug logging](https://confluence.atlassian.com/display/STASH0310/Stash+debug+logging)?

**Comment by t-8ch** [comment]
@RaviFIS Could you provide us the body of the request and response? Maybe using wireshark etc.

**Comment by kmoco2am** [comment]
We have probably similar issue where rule squid:S1451 tries to add comment on line "0" and the BitBucket server replies: "0 is not a valid line number. Diff lines start from 1."

**Comment by kmoco2am** [comment]
I have opened a PR for this: #96

**Comment by t-8ch** [comment]
Fair enough, #96 should fix this and will be available in the next release.
