### ISSUE TITLE
No issues received in SonarStash plugin

### ISSUE THREAD

**Issue by senty** [AmadeusITGroup/sonar-stash#43]
Hi !

I wanted to use this plugin. I have project where are we using maven sonar plugin + sonarqube 5.3. 
I have installed sonar starh plugin, setup stash url / user / password + installed sonnar-runner.

In stash i have created branch and pull request on which i have run sonnar-runner. Sonnar runner executed (as i was expecting) SonarStash plugin. He posted comment that pull request contains NO ERROR and approved pull request. 

But on purpose i have created some issue in branch.
1) In pull request in stash i can see change of code (errors in code)
2) In sonarqube i can see 3 new major issues (errors in code which i have made)
3) But Sonnar Stash posted no comment

I was little diging in code and in class 'StashIssueReportingPostJob' i have in contructor place little logging message how many issues contains property 'projectIssues' in constructor. Result is 0. Altogether my project is quite big and contains 650 critical + major issues (and 3 major are new created only in branch).

Do you have any ideas why SonarStash plugins does not receive any issues ?

Thank tou very much !

**Comment by acopet** [comment]
Hello @senty 

Could you please post the command line used to run your SQ analysis with the plugin?

Cheers,
Antoine

**Comment by senty** [comment]
Hi,

from project root directory :
`sonar-runner -Dsonar.branch=[STASH_BRANCH] -Dsonar.login=sonar -Dsonar.password=sonar -Dsonar.stash.notification -Dsonar.stash.project=[STASH_PROJECT] -Dsonar.stash.repository=[STASH_REPO] -Dsonar.stash.pullrequest.id=[STASH_PR_ID] -X`

Also i am adding 'export SONAR_RUNNER_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"' so i can debug it from IDE.

**Comment by acopet** [comment]
No analysis mode?

**Comment by senty** [comment]
Thank you very much for response ! I made some experiments ...

Configuration of sonar analyses i have in file 'sonar-project.properties'

`
sonar.projectKey = horec
sonar.projectName = Horec
sonar.projectVersion = 1.0
sonar.dynamicAnalysis = false
sonar.forceAnalysis = true
sonar.verbose = true

sonar.analysis.mode=publish

#source settings
sonar.sources = src/main/java
sonar.language = java
sonar.sourceEncoding = UTF-8

#modules settings
sonar.modules = [MODULES_TO_SCAN]
[HERE ARE PATHS e.g : module.sonar.projectBaseDir = my/path]

sonar.junit.reportsPath=target/surefire-reports
sonar.jacoco.reportPath=target/jacoco.exec
`

When i have switched analyss mode into issues or preview, issues were in sonar stash plugin. But no comments has been pushed into pull request. After debuging of SonarQubeCollector i have founded probably problem with inputFileCache :

Sonar analyses mode :
publish -> files are present (inside InputFileCache inputFileCache), but no issues
preview -> issues are in sonar stah plugin, but files not (InputFileCache inputFileCache is blank)
issues -> issues are in sonar stah plugin, but files not (InputFileCache inputFileCache is blank)

**Comment by senty** [comment]
No ideas why i am not receiving issues and files ?

**Comment by acopet** [comment]
Hello @senty,

Sorry for the delay to answer. Could you please replace your analysis mode from "publish" to "preview"?

Cheers,
Antoine

**Comment by acopet** [comment]
Hello @senty,

Any news on this issue?

Cheers,
Antoine

**Comment by acopet** [comment]
Close the ticket as there is no more activity.
To be reopened if the problem still occurs. 

Cheers,
Antoine
