### ISSUE TITLE
org.sonar.plugins.stash.exceptions.StashClientException: Unable to retrieve user userNAme. Received 404 with message Not Found.

### ISSUE THREAD

**Issue by aitvijay** [AmadeusITGroup/sonar-stash#48]
I am getting the Error

org.sonar.plugins.stash.exceptions.StashClientException: Unable to retrieve user <userName>. Received 404 with message Not Found.

**Comment by szpak** [comment]
The same here with Stash 3.9.2.

**Comment by szpak** [comment]
I've found the reason with a help of `-Dsonar.log.level=devel`. @nvillard Haven't you accidentally provided Stash URL with "/" at the end?

In that case "https://stash.server.foo//rest/api/1.0/users/someuser" is called what results with 404 Not found.

**Comment by acopet** [comment]
Hello @aitvijay,

Did the workaround provide by @szpak has solved your issue?
Have you updated the Stash url setting to delete "/" at the end?

Cheers,
Antoine
