### ISSUE TITLE
SonarQube 5.5 Compatibility

### ISSUE THREAD

**Issue by milindbangar79** [AmadeusITGroup/sonar-stash#54]
Hi,

Is the plugin compatible with SONARQube version 5.5.

I am not getting any issue in installing the plugin, but nothing seems to happen, while running the Sonar Jenkins job for a project.

It's a Maven build.

Any help will be great.

Thanks
Milind

**Comment by t-8ch** [comment]
Hi @milindbangar79, it should be compatible. Could you repeat your tests using 4.5.7 and check whether this helps?

**Comment by milindbangar79** [comment]
Hi,

I tried with 5.2,it seems to be working, but getting the following exception.

[ERROR] Unable to get Stash differential report from Stash: Unable to get comment linked to int.insurerriskfactors #10. Received 404 with message Not Found.
[ERROR] Process stopped: No Stash differential report available to process the SQ analysis

I am bit new to STASH, so can you help me what I would be doing wrong?

Thanks again..

Milind

**Comment by milindbangar79** [comment]
Closing the issue, as it's resolved now.

Issue was connectivity between SONARQube server and STASH on AWS.

Regards
Milind
