### ISSUE TITLE
Compatibility with Ant based builds/analyses

### ISSUE THREAD

**Issue by milindbangar79** [AmadeusITGroup/sonar-stash#57]
Is plugin compatible with ANT builds?

Thanks
Milind

**Comment by t-8ch** [comment]
The plugin itself can't be built directly using ANT.
It uses the offical `sonar-packaging-maven-plugin`, for which as far as I know no ANT equivalent exists.

**Comment by milindbangar79** [comment]
Sorry, my query was that can I use the plugin installed on SONAR server, which uses SONAR ant build to publish results on STASH.
Regards
Milind

**Comment by t-8ch** [comment]
Ah, that does indeed make sense.
It should work.
As long as you specify the relevant properties the plugin gets loaded from the SonarQube server.

**Comment by milindbangar79** [comment]
Hi while running the analysis, getting the following issue:

Target "<<sonar.stash.project>>" does not exist in the project "<<xyz>>". 

What could be the issue?

Regards
Milind

**Comment by t-8ch** [comment]
Did you define the propertue "sonar.stash.project" in you `build.xml`? Or supplied it via `-D`

**Comment by milindbangar79** [comment]
Yes, I supplied the variable within Jenkins build, same as for the Java one...

**Comment by milindbangar79** [comment]
Issue resolved by passing sonar.stash.notification explicitly as "true". Seems for ANT build , it takes the default value, but for MAVEN it does get set.

Can update the documentation with the same and close the issue.

**Comment by milindbangar79** [comment]
While publishing as comment on the code, I am getting the following message:

Comment "gosu-codenarc:org.codenarc.rule.gosu.GosuPrintStackTraceRule" cannot be pushed to Stash like it does not belong to diff view - modules/configuration/gsrc/com/gw/pc/lob/mtr/batch/SomeClass.gs (line: 62)

How to overcome this? Or enable it to be shown on STASH. The same issue I had with Maven build as well.

Thanks in advance.

Milind

**Comment by milindbangar79** [comment]
I see that there was similar issue #25 raised sometime back, for which solution provided is in following URL : https://github.com/kirkor/sonar-stash-test-project/blob/master/README.md

But this is also not helping me in seeing the issues in DIFF view.

I am using Plugin version 1.1.0

Regards
Milind

**Comment by t-8ch** [comment]
@milindbangar79 I am closing this issue. Please open a new ticket for your other issue and provide more information about the environment and configuration.
