### ISSUE TITLE
Cannot view Sonar Issues in DIFF view

### ISSUE THREAD

**Issue by milindbangar79** [AmadeusITGroup/sonar-stash#63]
Hi,

I have ANT (proprietary software runs on JVM) and MAVEN builds  (Spring Projects).

For either of them I am not able to view the issues on DIFF view.

I can see the issues on main view.

Went through forum and there were some issues created in past with  solution provided as part of following URL, but somehow does not work for me.

Related issues : #25

https://github.com/kirkor/sonar-stash-test-project/blob/master/README.md

Env : SonarQube V5.5 , JDK7 , Stash/BitBucket V4.x (SSL based : https://test.stash.com)

Regards
Milind

**Comment by milindbangar79** [comment]
Ok, with minor code change the paths' were same as below:

[sonar:sonar] Base to compare PATH ::::modules/configuration/gsrc/com/ukgi/gw/pc/lob/mtr/batch/MotoInsuranceDatabaseHeaderRecord.gs
[sonar:sonar] DIFF PATH ::::::modules/configuration/gsrc/com/ukgi/gw/pc/lob/mtr/batch/MotoInsuranceDatabaseHeaderRecord.gs
[sonar:sonar] TYPE ::::::ADDED

Got the following while POSTing of results to DIFF 

[sonar:sonar] Request DefaultHttpRequest(chunked: false)
[sonar:sonar] POST /rest/api/1.0/projects/UKGW/repos/policycentertest/pull-requests/4/comments HTTP/1.1
[sonar:sonar] Content-Type: application/json
[sonar:sonar] Content-Length: 393
[sonar:sonar] Connection: keep-alive
[sonar:sonar] Host: test.stash.com
[sonar:sonar] Authorization: Basic amVua2luc19wcm9kOlcxbG1hZGVhcmluZw==
[sonar:sonar] Accept: */*
[sonar:sonar] User-Agent: AHC/1.0
[sonar:sonar] 
[sonar:sonar] Response DefaultHttpResponse(chunked: true)
[sonar:sonar] HTTP/1.1 400 Bad Request
[sonar:sonar] Date: Thu, 01 Sep 2016 15:36:01 GMT
[sonar:sonar] X-AREQUESTID: @NAGML0x996x13601641x2
[sonar:sonar] X-ASEN: SEN-4246057
[sonar:sonar] X-AUSERID: 167
[sonar:sonar] X-AUSERNAME: jenkins_prod
[sonar:sonar] Cache-Control: no-cache, no-transform
[sonar:sonar] Vary: X-AUSERNAME,X-AUSERID,Cookie
[sonar:sonar] X-Content-Type-Options: nosniff
[sonar:sonar] Content-Type: application/json;charset=UTF-8
**[sonar:sonar] Connection: close**
[sonar:sonar] Transfer-Encoding: chunked
[sonar:sonar] Closing Channel [id: 0xd95c0b9e, /10.64.3.81:50548 => test.stash.com/10.48.186.145:443] 
[sonar:sonar] Channel Closed: [id: 0xd95c0b9e, /10.64.3.81:50548 :> test.stash.com/10.48.186.145:443] with attribute INSTANCE
**[sonar:sonar] Unable to link SonarQube issues to Stash: Unable to post a comment to policycentertest #4. Received 400 with message Bad Request.**
[sonar:sonar] Exception stack trace
[sonar:sonar] org.sonar.plugins.stash.exceptions.StashClientException: Unable to post a comment to policycentertest #4. Received 400 with message Bad Request.
[sonar:sonar] org.sonar.plugins.stash.exceptions.StashClientException: Unable to post a comment to policycentertest #4. Received 400 with message Bad Request.
[sonar:sonar] 	at org.sonar.plugins.stash.client.StashClient.postCommentLineOnPullRequest(StashClient.java:211) ~[sonar-stash-plugin-1.1.0.jar:na]
[sonar:sonar] 	at org.sonar.plugins.stash.StashRequestFacade.postCommentPerIssue(StashRequestFacade.java:171) ~[sonar-stash-plugin-1.1.0.jar:na]
[sonar:sonar] 	at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:85) [sonar-stash-plugin-1.1.0.jar:na]

Regards
Milind

**Comment by t-8ch** [comment]
Hi @milindbangar79 ,
Unfortunately the log is missing the information we need to resolve it...
Could you try it again with a version of this plugin with 4b40ab7 applied (latest master, or apply it some other version).
This should give us a proper error message.

This may be related to #42

**Comment by milindbangar79** [comment]
Thanks for the same.

Quick Question: The Tasks I am seeing now are on main view and not on DIFF.  Is this okay????

Regards
Milind

**Comment by t-8ch** [comment]
@milindbangar79 
I think tasks from the diff also appear in the overview. Could you can confirm that they are visible in both views?

**Comment by milindbangar79** [comment]
Hi, visible only on Overview page and not in Diff... 

Please find below the Request and Response. Did not get 400 problem...

Request Sent JSON BODY::::{"text":"*MINOR* - Define a constant instead of duplicating this literal \"C1RISK_VALUE12 ::\" 5 times. [[squid:S1192](http:\/\/10.64.54.77:8080\/coding_rules#rule_key=squid:S1192)]","anchor":{"lineType":"ADDED","fileType":"TO","path":"gw-insurerriskfactors-stub\/src\/main\/java\/com\/ukgi\/gw\/insurerriskfactors\/stub\/CreateRiskInsurerFactorResponseForC1Product.java","line":66}}
RESPONSE Received ::::::{"properties":{"repositoryId":4095},"id":79184,"version":0,"text":"*MINOR* - Define a constant instead of duplicating this literal \"C1RISK_VALUE12 ::\" 5 times. [[squid:S1192](http://10.64.54.77:8080/coding_rules#rule_key=squid:S1192)]","author":{"name":"jenkins_prod","emailAddress":"gicmtol@test.co.uk","id":167,"displayName":"Jenkins Prod","active":true,"slug":"jenkins_prod","type":"NORMAL","links":{"self":[{"href":"https://stash.test.com/users/**jenkins_prod**"}]}},"createdDate":1472812721658,"updatedDate":1472812721658,"comments":[],"tasks":[],"permittedOperations":{"**editable":true,"deletable":true**}}

Regards
Milind

**Comment by milindbangar79** [comment]
Is there any permission to be ascertained for tasks to appear on BitBucket?

**Comment by t-8ch** [comment]
@milindbangar79 If the user can do it via the website, it should be able to do it via the API.

Btw: in one of your [last comments](https://github.com/AmadeusITGroup/sonar-stash/issues/63#issuecomment-244138528) you leaked your SonarQube credentials in the the `Authorization` header. I changed them to fake ones but someone may have already gotten them, you should change your password.

**Comment by milindbangar79** [comment]
Thanks ... Updated...:-)

**Comment by milgoff** [comment]
@milindbangar79 do u still have this problem? I received the same.

**Comment by t-8ch** [comment]
Hi  @milgoff,
could you share more information?
* Which version of sonar-stash are you using?
* Do you encounter the `400 Bad Request` error
* Can you share debug logs (make sure to redact all confidential information, including the HTTP `Authorization` header, best just use a test instance of sonar/stash)
* Does your project consist of multiple modules
* Did you try [this](https://github.com/AmadeusITGroup/sonar-stash/pull/56#issuecomment-243452653)?

**Comment by t-8ch** [comment]
@milindbangar79 @milgoff 
Can you both try the latest master?
#96 should have fixed this.

**Comment by manojvai** [comment]
I am facing same issue. Below is my project details:

1. SonarQube 5.0.1
2. Sonar-stash-plugin-1.2.0.jar (Released Version)
3. MAVEN project structure:
         src
              |Module 1
                    |- src
                          |-main
                               |-impl
                                      |-services
                                              |- java
                                                    |- abc.java
              |Module 2
                    |- src
                          |-main
                               |- services
                                      |- abc.java

And goes on.....There are more than 10 modules on the project with sources on different folder structure.

We execute sonar analysis from Jenkins invoking mvn sonar:sonar. There is no sonar-properties.properties file.  below parameters are provide while invoking maven sonar analysis:
$SONAR_MAVEN_GOAL
-Dsonar.host.url=$SONAR_HOST_URL
-Dsonar.stash.project.base.dir=${WORKSPACE}
-Dsonar.stash.notification=true
-Dsonar.analysis.mode=incremental
-Dsonar.stash.project=san
-Dsonar.stash.repository=code-demo
-Dsonar.stash.pullrequest.id=${pullRequestId}
-Dsonar.stash.repository.root=${WORKSPACE}
-Dsonar.stash.login=*****
-Dsonar.stash.password=*****
-Dsonar.stash.include.overview=true
-Dsonar.language=java
       
Jenkins job completes successfully and Issues are posted in Overview Tab but fails to post in Diff View with error:

Executing post-job class org.******.plugins.stash.StashIssueReportingPostJob
16:15:50 [INFO] [16:15:56.932] Comment "8e6e836c-3b29-4435-93b5-9232699c3e6f" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/components/dto/***********.java (line: 201)
16:15:50 [INFO] [16:15:56.932] Comment "a1290d75-d423-4ea1-904f-5d9f581ddd35" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/components/dto/***********.java (line: 192)
16:15:50 [INFO] [16:15:56.932] Comment "a2069d71-307f-4ddd-8c4c-d078852c2ba6" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/components/dto/***********.java (line: 202)
16:15:50 [INFO] [16:15:56.932] Comment "b7a8fff4-720c-4680-b640-d6a7b8c24a3e" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/components/dto/***********.java (line: 193)
16:15:50 [INFO] [16:15:56.932] Comment "933fd515-847b-40d4-ac53-4c2f486e41b8" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/services/builders/********.java (line: 430)
16:15:50 [INFO] [16:15:56.932] Comment "5cadc3a1-44b4-4190-bf7a-99fdd226b983" cannot be pushed to Stash like it does not belong to diff view - products/auto/****-auto-comp/src/main/java/com/****/****/products/auto/services/impl/*******.java (line: 132)
16:15:50 [INFO] [16:15:56.932] Comment "e0388c8a-019c-4b8a-aecb-33283edf0142" cannot be pushed to Stash like it does not belong to diff view - products/common/****-common-services/src/main/java/com/****/****/products/common/services/tfs/******.java (line: 19)
16:15:50 [INFO] [16:15:56.932] New SonarQube issues have been reported to Stash.
16:15:50 [INFO] [16:15:57.021] SonarQube analysis overview has been reported to Stash.

I am stuck here and I looked at different post and it seems like there is a workaround available but the workaround is not clearly stated anywhere.

**Comment by kingoleg** [comment]
@ manojvai This is no workaround, you have to path sonar stash plugin or use my version from https://github.com/kingoleg/sonar-stash

**Comment by t-8ch** [comment]
@manojvai Can you try the latest master? The repository root setting was not in 1.2.0

**Comment by manojvai** [comment]
@t-8ch @kingoleg 

Tried both, the latest master and Kingoleg version - ran into below error in both versions. Error occurs at the beginning of sonar analysis.

14:03:01 [ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7:sonar (default-cli) on project aaa-parent: org.sonar.plugins.stash.coverage.CoverageProjectStore has unsatisfied dependency 'interface org.sonar.api.batch.rule.ActiveRules' for constructor 'public org.sonar.plugins.stash.coverage.CoverageProjectStore(org.sonar.plugins.stash.StashPluginConfiguration,org.sonar.api.batch.rule.ActiveRules)' from org.picocontainer.DefaultPicoContainer@298295dc:237<[Immutable]:org.picocontainer.DefaultPicoContainer@6949bd19:21<[Immutable]:org.picocontainer.DefaultPicoContainer@1eca043e:109<| -> [Help 1]
14:03:01 [ERROR]

**Comment by kingoleg** [comment]
@manojvai what jar name did you use from /target/? There are two of them there. Try other one

**Comment by manojvai** [comment]
@kingoleg 

Same error with both jars -kingoleg-original-sonar-stash-plugin-1.3.0-SNAPSHOT.jar & sonar-stash-plugin-1.3.0-SNAPSHOT.jar

[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7:sonar (default-cli) on project aaa-parent: org.sonar.plugins.stash.coverage.CoverageProjectStore has unsatisfied dependency 'interface org.sonar.api.batch.rule.ActiveRules' for constructor 'public org.sonar.plugins.stash.coverage.CoverageProjectStore(org.sonar.plugins.stash.StashPluginConfiguration,org.sonar.api.batch.rule.ActiveRules)' from org.picocontainer.DefaultPicoContainer@2c100d11:237<[Immutable]:org.picocontainer.DefaultPicoContainer@1f70ef11:21<[Immutable]:org.picocontainer.DefaultPicoContainer@16559fbb:109<| -> [Help 1]
16:48:50 [ERROR]

**Comment by t-8ch** [comment]
@manojvai Ah, you are using an unsuppored version of SonarQube.
1.3.0 requires at least 5.6. (It may also work with 5.2)

**Comment by t-8ch** [comment]
This should be fixed in the latest versions.

@manojvai Yuo are seeing a different issue than the ticket is about. If this is not fixed by using a supported version of SonarQube, please open a new ticket.
