### ISSUE TITLE
How to invoke code coverage build profile?

### ISSUE THREAD

**Issue by milindbangar79** [AmadeusITGroup/sonar-stash#68]
Hi,

How can we invoke "coverage-per-test" from within Jenkins Build?

I am getting the following warning 

[WARNING] The requested profile "coverage-per-test" could not be activated because it does not exist.

Added the Profile within settings.xml, but no luck.

Regards
Milind

**Comment by t-8ch** [comment]
Hi @milindbangar79,

Are you building your own project or this plugin?
This profile is a special one defined in the [pom.xml of this project](https://github.com/AmadeusITGroup/sonar-stash/blob/5f0256baf0eb3e5e3b9bd932a770b268be49cb1f/pom.xml#L208).
It will not work out of the box for your project.
