### ISSUE TITLE
Option for creating a task on the issue comment

### ISSUE THREAD

**Issue by juherr** [AmadeusITGroup/sonar-stash#7]
I like to add a task with my review message in order to keep a trace about remaining work.

It will help me if the sonar bot is be able to do it too :)

**Comment by sleeper** [comment]
Good idea !

**Comment by acopet** [comment]
I am little bit afraid of this option will not be so easy to implement.
After having a look to the documentation, Stash Rest API does not expose any action to create a task on a comment (only getter available)...

**Comment by juherr** [comment]
POST on `/rest/api/1.0/tasks` should work.

I tried to see what Stash is doing via its UI and the POST request had the following payload:

```json
{
  "anchor": {"id": 7186,"type": "COMMENT"},
  "pullRequestId": 226,
  "repositoryId": 3,
  "text": "test",
  "state": "OPEN",
  "pendingSync": true,
  "permittedOperations": {}
}
```

**Comment by racodond** [comment]
For your information, it is implemented in https://github.com/racodond/sonar-stash. Note that this feature can be activated starting at a specific severity threshold (CRITICAL by default).

See https://github.com/racodond/sonar-stash/commit/51a61e93d7ccc5cbb439163de15a4f9f41b2214a and https://github.com/racodond/sonar-stash/commit/ced045325ec516a6c342e7dc1851367cd528014a. Thanks to @Eernie for this contribution.

**Comment by juherr** [comment]
@racodond Great! But why not pull-requesting it here?

**Comment by racodond** [comment]
@juherr The big issue is that there's starting to be too many differences between the repositories.

**Comment by acopet** [comment]
**Pull-request #33 created to integrate this feature.**
Thnk you very much @racodond for your contribution.

**Comment by acopet** [comment]
**Feature available on master branch and will be release soon with plugin version 1.1.0.**
