### ISSUE TITLE
Bamboo integration

### ISSUE THREAD

**Issue by kingoleg** [AmadeusITGroup/sonar-stash#75]
Hi,

Is there any documentation how to integration the plugin with bamboo?

Regards,
Oleg

**Comment by t-8ch** [comment]
It should be like any other plugin.
We did not test it with bamboo but it probably depends on the build system (maven/ant/sonar-scanner) you are using inside bamboo.
You have to deploy the plugin to bamboo server and then provide the relevant properties, please read the documentation for the build system you are using.

**Comment by kingoleg** [comment]
I was able to integrate sonar, bitbucket and bamboo via https://github.com/tomasbjerre/pull-request-notifier-for-bitbucket
