### ISSUE TITLE
Wait for feedback for the 1.2.0 release candidates

### ISSUE THREAD

**Issue by t-8ch** [AmadeusITGroup/sonar-stash#86]
This issue is meant to send  notifications to all repo watchers that a new [release candidate](https://github.com/AmadeusITGroup/sonar-stash/releases/tag/1.2.0-rc1) has been published.

The deadline for feedback is 2016-10-14.

For future notifications and updates for releases please subscribe to the [releases atom feed](https://github.com/AmadeusITGroup/sonar-stash/releases.atom)

**Comment by re-schneider** [comment]
Release 1.2.0 done today
