### ISSUE TITLE
manifest issue

### ISSUE THREAD

**Issue by zippy-pl** [AmadeusITGroup/sonar-stash#87]
Dear All
i just tested snapshot and stable plugins and something doesnt work for me:( any clues? how to debug it?
On stash i see msg no issues detected but something else look like from command line and my pull request has violations for sure:)
btw really nice plugin! thanks for it

regards 
luke

DEBUG: Detection of duplications for xxxx:xxstorefront2-web:web/src/com/xx/xxx/storefront2/forms/valida
tion/SecuredTokenNotMatchAttrValidator.java
DEBUG: Detection of duplications for xxxx:xxstorefront2-web:web/src/com/xx/xxx/storefront2/security/Rem
emberMeAuthenticationProvider.java
DEBUG: Detection of duplications for xxxx:xxstorefront2-web:web/src/com/xx/xxx/storefront2/forms/valida
tion/EqualAttributes.java
DEBUG: Detection of duplications for xxxx:xxstorefront2-web:web/src/com/xx/xxx/storefront2/controllers/
ControllerConstants.java
INFO: CPD calculation finished
INFO: Analysis report generated in 5581ms, dir size=2 MB
INFO: Analysis reports compressed in 1519ms, zip size=1 MB
DEBUG: Upload report
DEBUG: POST 200 xxxxxxxxx.xx.com:9000/api/ce/submit?projectKey=xxxx&projectName=xxxx | time=713ms

INFO: Analysis report uploaded in 717ms
INFO: ANALYSIS SUCCESSFUL, you can browse xxxxxxxxx.xx.com:9000/dashboard/index/xxxx
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted a
nalysis report
INFO: More about the report processing at xxxxxxxxx.xx.com:9000/api/ce/task?id=AVfcnVQ0xxxx86M93
1rPI
DEBUG: Report metadata written to C:\Users\xxxxx\Desktop\xx\xx\src\xxxxxxxxxx\bin\custom\xx\.sonar\repo
rt-task.txt
DEBUG: Post-jobs : org.sonar.plugins.stash.StashIssueReportingPostJob@1d4f63b
INFO: Executing post-job org.sonar.plugins.stash.StashIssueReportingPostJob
DEBUG: Using non-cached Channel [id: 0xf403ca23, /xxxxxxx:54349 => stash.xx.com/xxxxxx:443] for GET
 '/rest/api/1.0/users/xxxxx'
DEBUG:

Request DefaultHttpRequest(chunked: false)
GET /rest/api/1.0/users/xxxxx HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Host: stash.xx.com
Authorization: Basic xxxxxxxx
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: true)
HTTP/1.1 200 OK
Date: Wed, 19 Oct 2016 11:04:41 GMT
Server: Apache-Coyote/1.1
X-AREQUESTID: @xxxxxxxxxxx
X-ASEN: SEN-7900221
X-AUSERID: 1229
X-AUSERNAME: xxxxx
Cache-Control: no-cache, no-transform
Vary: X-AUSERNAME,Accept-Encoding
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
Connection: close
Transfer-Encoding: chunked

DEBUG: Closing Channel [id: 0xf403ca23, /xxxxxxx:54349 => stash.xx.com/xxxxxx:443]
DEBUG: Channel Closed: [id: 0xf403ca23, /xxxxxxx:54349 :> stash.xx.com/xxxxxx:443] with attribute I
NSTANCE
DEBUG: SonarQube reviewer xxxxx identified in Stash
DEBUG: Using non-cached Channel [id: 0x0aac870d, /xxxxxxx:54385 => stash.xx.com/xxxxxx:443] for GET
 '/rest/api/1.0/projects/xxx/repos/xxx/pull-requests/3051/diff?withComments=true'
DEBUG:

Request DefaultHttpRequest(chunked: false)
GET /rest/api/1.0/projects/xxx/repos/xxx/pull-requests/3051/diff?withComments=true HTTP/1.1
Content-Type: application/json
Connection: keep-alive
Host: stash.xx.com
Authorization: Basic xxxxxxxx
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: true)
HTTP/1.1 200 OK
Date: Wed, 19 Oct 2016 11:04:41 GMT
Server: Apache-Coyote/1.1
X-AREQUESTID: @XMR1PUx664x1377555x0
X-ASEN: SEN-7900221
X-AUSERID: 1229
X-AUSERNAME: xxxxx
Cache-Control: no-cache, no-transform
Vary: X-AUSERNAME,Accept-Encoding
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
Connection: close
Transfer-Encoding: chunked

DEBUG: Closing Channel [id: 0x0aac870d, /xxxxxxx:54385 => stash.xx.com/xxxxxx:443]
DEBUG: Channel Closed: [id: 0x0aac870d, /xxxxxxx:54385 :> stash.xx.com/xxxxxx:443] with attribute I
NSTANCE
DEBUG: Stash differential report retrieved from pull request xxx #3051
INFO: SonarQube issues reported to Stash by user "xxxxx" have been reset
INFO: New SonarQube issues have been reported to Stash.
DEBUG: Using non-cached Channel [id: 0x87911134, /xxxxxxx:54421 => stash.xx.com/xxxxxx:443] for POS
T '/rest/api/1.0/projects/xxx/repos/xxx/pull-requests/3051/comments'
DEBUG:

Request DefaultHttpRequest(chunked: false)
POST /rest/api/1.0/projects/xxx/repos/xxx/pull-requests/3051/comments HTTP/1.1
Content-Type: application/json
Content-Length: 70
Connection: keep-alive
Host: stash.xx.com
Authorization: Basic xxxxxxxx
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: true)
HTTP/1.1 201 Created
Date: Wed, 19 Oct 2016 11:04:41 GMT
Server: Apache-Coyote/1.1
X-AREQUESTID: @XMR1PUx664x1377556x0
X-ASEN: SEN-7900221
X-AUSERID: 1229
X-AUSERNAME: xxxxx
Location: https://stash.xx.com/rest/api/1.0/projects/xxx/repos/xxx/pull-requests/3051/comments/25061
Cache-Control: no-cache, no-transform
Vary: X-AUSERNAME,Accept-Encoding
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
Connection: close
Transfer-Encoding: chunked

DEBUG: Closing Channel [id: 0x87911134, /xxxxxxx:54421 => stash.xx.com/xxxxxx:443]
DEBUG: Channel Closed: [id: 0x87911134, /xxxxxxx:54421 :> stash.xx.com/xxxxxx:443] with attribute I
NSTANCE
INFO: SonarQube analysis overview has been reported to Stash.
INFO: Task total time: 1:43.291 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------

**Comment by zippy-pl** [comment]
sorry resolved:) went into debug mode and found only new issues are reported...
thx 

btw have now other problem. With the latest version of plugin there is some manifest issue? have you seen it?

DEBUG: Post-jobs : org.sonar.plugins.stash.StashIssueReportingPostJob@1f49ab8
INFO: Executing post-job org.sonar.plugins.stash.StashIssueReportingPostJob
WARN: Exception detected: Can not call newInstance() on the Class for java.lang.Class
DEBUG: Exception stack trace
java.lang.IllegalAccessException: Can not call newInstance() on the Class for java.lang.Class
        at java.lang.Class.newInstance(Class.java:406) ~[na:1.8.0_91]
        at org.sonar.plugins.stash.PluginUtils.classesMatching(PluginUtils.java:64) [sonar-stash-plugin-1.2.0-
SNAPSHOT.jar:na]
        at org.sonar.plugins.stash.PluginUtils.infoForPluginClass(PluginUtils.java:40) [sonar-stash-plugin-1.2
.0-SNAPSHOT.jar:na]
        at org.sonar.plugins.stash.client.StashClient.getUserAgent(StashClient.java:343) [sonar-stash-plugin-1
.2.0-SNAPSHOT.jar:na]
        at org.sonar.plugins.stash.client.StashClient.createHttpClient(StashClient.java:359) [sonar-stash-plug
in-1.2.0-SNAPSHOT.jar:na]
        at org.sonar.plugins.stash.client.StashClient.<init>(StashClient.java:78) [sonar-stash-plugin-1.2.0-SN
APSHOT.jar:na]
        at org.sonar.plugins.stash.StashIssueReportingPostJob.executeOn(StashIssueReportingPostJob.java:54) [s
onar-stash-plugin-1.2.0-SNAPSHOT.jar:na]
        at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:63) [sonar-scanner-engine-s
haded-6.0.jar:na]
        at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:53) [sonar-scanner-engine-s
haded-6.0.jar:na]
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:82) [sonar-scanne
r-engine-shaded-6.0.jar:na]
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184) [sonar-scanne
r-engine-shaded-6.0.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scan
ner-engine-shaded-6.0.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engi
ne-shaded-6.0.jar:na]
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engi
ne-shaded-6.0.jar:na]
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-s

**Comment by t-8ch** [comment]
@zippy-pl 
Thanks for the notification about the error!
The code (and the tests) were broken and have been fixed.
