### ISSUE TITLE
Allow to exclude rules to be reported as comments

### ISSUE THREAD

**Issue by christiangalsterer** [AmadeusITGroup/sonar-stash#89]
In some situation it is helpful to exclude rules to be reported as comments even if they are configured in the SonarQube quality profile.

One example is that you automatically add a license disclaimer in your source code in a highly build and have that check configured in your quality profile but don't want to see them as comment as Bitbucket as you know that it will be added later on automatically.

**Comment by t-8ch** [comment]
Closing in favor of #97
