### ISSUE TITLE
Allow to break the build if there are issues that need attention

### ISSUE THREAD

**Issue by ghenzler** [AmadeusITGroup/sonar-stash#91]
So obviously it is great to see the violations in Stash, but it would be great to also break the build to stop the Jenkins pipeline at this step. 

For Sonar 5.3 there is also the build breaker plugin to achieve that, however that breaks the build only for full (non-preview) analysis runs. Also the build breaker plugin waits for the analysis to finsh while this plugin seems to be able to evalutate the result immediately (I believe this is because sonar-stash is not checking the quality gate but "only" simple issues on particular files). 

So I suggest introducing a config flag that if it is set to true, will simple break the build after pushing the issues to stash. Breaking the build should be a matter of throwing an exception (compare https://github.com/SonarQubeCommunity/sonar-build-breaker/blob/2.1/src/main/java/org/sonar/plugins/buildbreaker/QualityGateBreaker.java#L184 for this)

**Comment by t-8ch** [comment]
I think this functionality does not belong into this plugin.
Whatever is missing should be implemented in the build breaker plugin or a new plugin.
