### ISSUE TITLE
Allow to specify git branch instead of pull request id

### ISSUE THREAD

**Issue by ghenzler** [AmadeusITGroup/sonar-stash#92]
In a jenkins pipeline, the value for `sonar.stash.pullrequest.id` is not readily available. It would be great to be able to specify `sonar.stash.pullrequest.branch` (available via `${BRANCH_NAME}`) and have sonar-stash automatically derive the PR id using the Stash API.

**Comment by t-8ch** [comment]
Hi @ghenzler,

it seems there is no direct API on bitbucket to map a branch to a pullrequest (only the other way around).
What are you using to trigger the builds on pullrequests? It should allow you to pass additional metadata.

**Comment by ghenzler** [comment]
@t-8ch We use a variant of [1] to trigger Jenkins. There are other plugins as well, but they all use the servlet provided by the jenkins git plugin [2]. IMHO that servlet does not allow to pass through additional arguments that become readily available in the Jenkins pipeline, hence it would be really useful to be able to specify branch name instead of the PR ID.

There is an easy to use API to map branch name to PR ID, see [3] for the tested and working code references of my PR.

[1] https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook
[2] https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin

[3] 
https://github.com/ghenzler/sonar-stash/blob/6e271e3eac31f2b4f8528cd0b15369870cdec023/src/main/java/org/sonar/plugins/stash/client/StashClient.java#L190
https://github.com/ghenzler/sonar-stash/blob/6e271e3eac31f2b4f8528cd0b15369870cdec023/src/main/java/org/sonar/plugins/stash/StashRequestFacade.java#L265

**Comment by jannylund** [comment]
I have a similar need with running Bitbucket Server, Bamboo + Sonar. Bamboo triggers on repo changes, but can not easily get the ID of a PR. (I shellscripted around it with git ls-remote..., but this would make life easier). Bitbucket Server sadly doesn't seem to have any way of triggering Bamboo on PR creation.

**Comment by t-8ch** [comment]
@ghenzler Should we not match by both source and destination branch?
It is possible to have multiple Pull requests from one source branch.

I prefer the explicit approach over one where it may fail in some cases.
Would this help, @ghenzler and @jannylund ?

**Comment by jannylund** [comment]
@t-8ch since bitbucket can not trigger a build on PR creation, the build is not aware of the destination branch (though in my current workflow we run with github-flow, so merging always goes towards master). I'm not sure how an optimal solution would look right now.

**Comment by t-8ch** [comment]
@ghenzler 
It should be possible to submit more information via the servlet.
https://github.com/jenkinsci/git-plugin/blob/c60027f816fcd32df7cd0917921ab111782e8709/src/main/java/hudson/plugins/git/GitStatus.java#L132

The problem is, that the webhook is not authenticated, so you would have to first enable parameters via the webhook and then also whitelist the custom parameter you need.
This probably also needs patches to the stash plugin.

**Comment by t-8ch** [comment]
@jannylund 
There seems to be a 3rd party plugin which can provide this functionality.
https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash/server/overview

If the official bridge between bitbucket and bamboo does not include this information I would recommend opening this with Atlassian.
I understand the request for this, but as the mechanism is not bulletproof I would prefer a solution that always works.

**Comment by jannylund** [comment]
@t-8ch thanks, I wasn't aware of that one. Good find. If this plugin works, then I'm completely ok with the solution to require both target and destination branches in the analysis.

**Comment by t-8ch** [comment]
@jannylund , in this case it should also be fine to require the pull request number itself, no?

**Comment by jannylund** [comment]
As I'm working with Bamboo, there's a full workaround for the variable part now, and I got hope this will become default features in the future of Bamboo as seen here: https://jira.atlassian.com/browse/BAM-18350

**Comment by datasmurfen** [comment]
Would made things so much easier to look for pull request on branch name instead of the id :(  Since there is a lot of different build agents out today.

**Comment by t-8ch** [comment]
@datasmurfen as for the reasons outlined in this issue going via tha branch name is actually not a generic solution.
