### ISSUE TITLE
Issue with pull-requests formatting

### ISSUE THREAD

**Issue by mkj28** [AmadeusITGroup/sonar-stash#98]
Seeing this on stash side:
ERROR "GET /rest/api/1.0/projects/proj/repos/repo/pull-requests/10,997/diff HTTP/1.1" c.a.s.i.r.e.DefaultUnhandledExceptionMapperHelper Unhandled exception while processing REST request: "GET /rest/api/1.0/projects/proj/repos/repo/pull-requests/10,997/diff HTTP/1.1"
java.lang.NumberFormatException: For input string: "10,997"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_60]
	at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_60]
	at java.lang.Long.parseLong(Long.java:631) ~[na:1.8.0_60]

**Comment by mkj28** [comment]
Something like this:
```java
diff --git a/src/main/java/org/sonar/plugins/stash/client/StashClient.java b/src/main/java/org/sonar/plugins/stash/client/StashClient.java
index e54292c..85e1c46 100755
--- a/src/main/java/org/sonar/plugins/stash/client/StashClient.java
+++ b/src/main/java/org/sonar/plugins/stash/client/StashClient.java
@@ -51,7 +54,7 @@ public class StashClient implements AutoCloseable {
   private static final String TASKS_API = REST_API + "tasks";
 
   private static final String API_ALL_PR = REPO_API + "pull-requests/";
-  private static final String API_ONE_PR = API_ALL_PR + "{3}";
+  private static final String API_ONE_PR = API_ALL_PR + "{3,number,#}";
 
   private static final String API_ONE_PR_ALL_COMMENTS = API_ONE_PR + "/comments";
   private static final String API_ONE_PR_DIFF = API_ONE_PR + "/diff?withComments=true";
```

**Comment by t-8ch** [comment]
@mkj28 Which version of the plugin are you using?
I would like to find out how the pull request number became a floating point number.

**Comment by t-8ch** [comment]
The new version will use ints interally for the pull request id.
Can you show me the command line you are using to call the plugin?
The pull request id should be passed down directly from the configuration, without any modification

**Comment by mkj28** [comment]
@t-8ch I'm using 1.3.0. 

I think it becomes formatted in StashClient.java:
String request = MessageFormat.format(API_ONE_PR_DIFF, baseUrl, pr.project(), pr.repository(), pr.pullRequestId());

http://stackoverflow.com/questions/1942118/how-do-i-format-a-long-integer-as-a-string-without-separator-in-java

**Comment by t-8ch** [comment]
@mkj28 , ah misunderstood the issue. You are of course right and fix is is correct.
A regarded the comma as a decimal separator (I am from Europe) and was wondering where you got a PR of 10.997 from.
